class XtdGearModels {
    class CfgWeapons {
        class 19th_br_55 {
            label = "[19th] BR-55";
            options[] = {"Underbarrel"};
            class Underbarrel {
                label = "Underbarrel Attachment";
                values[] = {"None", "GL"};

                class None {
                    description = "Standard loadout.";
                };

                class GL {
                    description = "Underbarrel grendade launcher.";
                };
            };
        };
    };
};
