class CfgMagazineWells
{
  class OPTRE_Magwell_M247
  {
    DMNS_Magazines[] = {
      "DMNS_100Rnd_762x51_Mag_GPMG"
      , "DMNS_100Rnd_762x51_Mag_GPMG_Tracer"
      , "DMNS_200Rnd_762x51_Mag_GPMG"
      , "DMNS_200Rnd_762x51_Mag_GPMG_Tracer"
      , "DMNS_400Rnd_762x51_Mag_GPMG"
      , "DMNS_400Rnd_762x51_Mag_GPMG_Tracer"
    };
  };

  class OPTRE_Magwell_MA5A
  {
    DMNS_Magazines[] = {
      "32Rnd_762x51_MA5"
      , "32Rnd_762x51_MA5_AP"
      , "32Rnd_762x51_MA5_tracer"
      , "32Rnd_762x51_MA5_AP_tracer"
    };
  };

  class OPTRE_Magwell_MA5B
  {
    DMNS_Magazines[] = {
      "32Rnd_762x51_MA5"
      , "32Rnd_762x51_MA5_AP"
      , "32Rnd_762x51_MA5_tracer"
      , "32Rnd_762x51_MA5_AP_tracer"
    };
  };
};
