class CfgWorlds {
	class VR;
  class SWS_VR_Space: VR {
		description = "HIP 58494";
    horizontObject = "OPTRE_Phobos\data\files\horizont.p3d";
    loadingTexts[] = {"HIP 58494 is a system in the Orio-Persian Gap. How did you even get out here?"};
    skyObject = "OPTRE_Phobos\data\files\sky.p3d";
    skyTexture = "\x\sws\addons\terrain\vr_space\data\spacebox.paa";
    class Weather: Weather {
      class Overcast: Overcast {
        class Weather1 {
          overcast = 0;
					cloudiness = 0;
					alpha = 0;
					lightingOvercast = 0;
					waves = 0;
					bright = 0.5;
					speed = 0;
					size = 0;
					height = 1;
					through = 1;
					diffuse = 1;
					cloudDiffuse = 0;
					sky = "\x\sws\addons\terrain\vr_space\data\spacebox.paa";
					skyR = "OPTRE_Phobos\data\spaceboxR.paa";
        };
        class Weather2
				{
					overcast = 0;
					cloudiness = 0;
					alpha = 0;
					lightingOvercast = 0;
					waves = 0;
					bright = 0.5;
					speed = 0;
					size = 0;
					height = 1;
					through = 1;
					diffuse = 1;
					cloudDiffuse = 0;
					sky = "\x\sws\addons\terrain\vr_space\data\spacebox.paa";
					skyR = "OPTRE_Phobos\data\spaceboxR.paa";
				};
				class Weather3
				{
					overcast = 0;
					cloudiness = 0;
					alpha = 0;
					lightingOvercast = 0;
					waves = 0;
					bright = 0.5;
					speed = 0;
					size = 0;
					height = 1;
					through = 1;
					diffuse = 1;
					cloudDiffuse = 0;
					sky = "\x\sws\addons\terrain\vr_space\data\spacebox.paa";
					skyR = "OPTRE_Phobos\data\spaceboxR.paa";
				};
				class Weather4
				{
					overcast = 0;
					cloudiness = 0;
					alpha = 0;
					lightingOvercast = 0;
					waves = 0;
					bright = 0.5;
					speed = 0;
					size = 0;
					height = 1;
					through = 1;
					diffuse = 1;
					cloudDiffuse = 0;
					sky = "\x\sws\addons\terrain\vr_space\data\spacebox.paa";
					skyR = "OPTRE_Phobos\data\spaceboxR.paa";
				};
				class Weather5
				{
					overcast = 0;
					cloudiness = 0;
					alpha = 0;
					lightingOvercast = 0;
					waves = 0;
					bright = 0.5;
					speed = 0;
					size = 0;
					height = 1;
					through = 1;
					diffuse = 1;
					cloudDiffuse = 0;
					sky = "\x\sws\addons\terrain\vr_space\data\spacebox.paa";
					skyR = "OPTRE_Phobos\data\spaceboxR.paa";
				};
				class Weather6
				{
					overcast = 0;
					cloudiness = 0;
					alpha = 0;
					lightingOvercast = 0;
					waves = 0;
					bright = 0.5;
					speed = 0;
					size = 0;
					height = 1;
					through = 1;
					diffuse = 1;
					cloudDiffuse = 0;
					sky = "\x\sws\addons\terrain\vr_space\data\spacebox.paa";
					skyR = "OPTRE_Phobos\data\spaceboxR.paa";
				};
      };
    };
	};
};



