class CfgMagazineWells {
  class UGL_40x36 {
    SUBGVAR(Magazines)[] = {"SWS_Magazine_Grenade_M3Sx_1Rnd_Shell"};
  };

  class 3UGL_40x36 {
    SUBGVAR(Magazines)[] = {"SWS_Magazine_Grenade_M3Sx_3Rnd_Shell"};
  };

  class CBA_40mm_M203 {
    SUBGVAR(Magazines)[] = {"SWS_Magazine_Grenade_M3Sx_1Rnd_Shell"};
  };

  class CBA_40mm_3GL {
    SUBGVAR(Magazines)[] = {"SWS_Magazine_Grenade_M3Sx_3Rnd_Shell"};
  };
};
