class CfgVehicles {
  class Bag_Base;

  class TFAR_RT1523G : Bag_Base {
    SCOPE(0);
    displayName = "Dummy Item - Used for compatibility with UNSC Foundries backpacks.";
  };

  class 19th_H2A_Marine_Backpack_Heavy_RTO : Bag_Base {};
  class 19th_H2A_Marine_Backpack_Light_RTO : Bag_Base {};
  class 19th_H2A_Marine_Backpack_RTO : Bag_Base {};
  class 19thMD_Backpack_Standard_rto : Bag_Base {};
  class 19thMD_Backpack_Standard_rto_heavy : Bag_Base {};
};
