class GRENADE(M3Sx): OPTRE_G_M9_Frag {
    META;
    hit = 40;
    indirectHit = 40;
    indirectHitRange = 7;
    ace_frag_gurney_c = 3000;
    ace_frag_gurney_k = "1/2";
    ace_frag_classes[] = {"ACE_frag_small_HD"};
    ace_frag_metal = 180;
    ace_frag_charge = 300;
    ace_frag_enabled = 1;
};

class SHELL(M3Sx_40mm): M319_HE {
    META;
    hit = 40;
    indirectHit = 40;
    indirectHitRange = 7;
    ace_frag_gurney_c = 3000;
    ace_frag_gurney_k = "1/2";
    ace_frag_classes[] = {"ACE_frag_small_HD"};
    ace_frag_metal = 180;
    ace_frag_charge = 300;
    ace_frag_enabled = 1;
};
