hiddenSelectionsTextures[] = {
  "V_FZ_Ground_Vehicles\data\Scorpion\V_M808_OD3_CO.paa"
  , "V_FZ_Ground_Vehicles\data\Scorpion\V_M808_OD3_T_CO.paa"
  , "V_FZ_Ground_Vehicles\data\Scorpion\V_M808_OD3_D3_CO.paa"
  , "Optre_Vehicles_Tracked\Scorpion\data\texture\scorp_decals_ca.paa"
  , "Optre_Vehicles_Tracked\Scorpion\data\texture\scorp_net_wood_ca.paa"
  , "Optre_Vehicles_Tracked\Scorpion\data\texture\scorp_net_wood_ca.paa"
  , "V_FZ_Ground_Vehicles\data\Scorpion\V_M808_OD3_MR_CO.paa"
  , "V_FZ_Ground_Vehicles\data\Oryx\V_M494_OD3_MG_CO.paa"
};

class TextureSources {
  class VES_Desert {
    textures[] = {
      "V_FZ_Ground_Vehicles\data\Scorpion\V_M808_DES_CO.paa"
      , "V_FZ_Ground_Vehicles\data\Scorpion\V_M808_DES_T_CO.paa"
      , "V_FZ_Ground_Vehicles\data\Scorpion\V_M808_DES_D3_CO.paa"
      , "Optre_Vehicles_Tracked\Scorpion\data\texture\scorp_decals_ca.paa"
      , "Optre_Vehicles_Tracked\Scorpion\data\texture\scorp_net_wood_ca.paa"
      , "Optre_Vehicles_Tracked\Scorpion\data\texture\scorp_net_wood_ca.paa"
      , "V_FZ_Ground_Vehicles\data\Scorpion\V_M808_DES_MR_CO.paa"
      , "V_FZ_Ground_Vehicles\data\Oryx\V_M494_DES_MG_CO.paa"
    };
  };
  class VES_Woodland {
    textures[] = {
      "V_FZ_Ground_Vehicles\data\Scorpion\V_M808_WDL_CO.paa"
      , "V_FZ_Ground_Vehicles\data\Scorpion\V_M808_WDL_T_CO.paa"
      , "V_FZ_Ground_Vehicles\data\Scorpion\V_M808_WDL_D3_CO.paa"
      , "Optre_Vehicles_Tracked\Scorpion\data\texture\scorp_decals_ca.paa"
      , "Optre_Vehicles_Tracked\Scorpion\data\texture\scorp_net_wood_ca.paa"
      , "Optre_Vehicles_Tracked\Scorpion\data\texture\scorp_net_wood_ca.paa"
      , "V_FZ_Ground_Vehicles\data\Scorpion\V_M808_WDL_MR_CO.paa"
      , "V_FZ_Ground_Vehicles\data\Oryx\V_M494_WDL_MG_CO.paa"
    };
  };
  class VES_Jungle {
    textures[] = {
      "V_FZ_Ground_Vehicles\data\Scorpion\V_M808_JUN_CO.paa"
      , "V_FZ_Ground_Vehicles\data\Scorpion\V_M808_JUN_T_CO.paa"
      , "V_FZ_Ground_Vehicles\data\Scorpion\V_M808_JUN_D3_CO.paa"
      , "Optre_Vehicles_Tracked\Scorpion\data\texture\scorp_decals_ca.paa"
      , "Optre_Vehicles_Tracked\Scorpion\data\texture\scorp_net_wood_ca.paa"
      , "Optre_Vehicles_Tracked\Scorpion\data\texture\scorp_net_wood_ca.paa"
      , "V_FZ_Ground_Vehicles\data\Scorpion\V_M808_JUN_MR_CO.paa"
      , "V_FZ_Ground_Vehicles\data\Oryx\V_M494_JUN_MG_CO.paa"
    };
  };
  class VES_Urban {
    textures[] = {
      "V_FZ_Ground_Vehicles\data\Scorpion\V_M808_URB_CO.paa"
      , "V_FZ_Ground_Vehicles\data\Scorpion\V_M808_URB_T_CO.paa"
      , "V_FZ_Ground_Vehicles\data\Scorpion\V_M808_URB_D3_CO.paa"
      , "Optre_Vehicles_Tracked\Scorpion\data\texture\scorp_decals_ca.paa"
      , "Optre_Vehicles_Tracked\Scorpion\data\texture\scorp_net_wood_ca.paa"
      , "Optre_Vehicles_Tracked\Scorpion\data\texture\scorp_net_wood_ca.paa"
      , "V_FZ_Ground_Vehicles\data\Scorpion\V_M808_URB_MR_CO.paa"
      , "V_FZ_Ground_Vehicles\data\Oryx\V_M494_URB_MG_CO.paa"
    };
  };
  class VES_Black {
    textures[] = {
      "V_FZ_Ground_Vehicles\data\Scorpion\V_M808_BLK_CO.paa"
      , "V_FZ_Ground_Vehicles\data\Scorpion\V_M808_BLK_T_CO.paa"
      , "V_FZ_Ground_Vehicles\data\Scorpion\V_M808_BLK_D3_CO.paa"
      , "Optre_Vehicles_Tracked\Scorpion\data\texture\scorp_decals_ca.paa"
      , "Optre_Vehicles_Tracked\Scorpion\data\texture\scorp_net_wood_ca.paa"
      , "Optre_Vehicles_Tracked\Scorpion\data\texture\scorp_net_wood_ca.paa"
      , "V_FZ_Ground_Vehicles\data\Scorpion\V_M808_BLK_MR_CO.paa"
      , "V_FZ_Ground_Vehicles\data\Oryx\V_M494_BLK_MG_CO.paa"
    };
  };
  class VES_Frost {
    textures[] = {
      "V_FZ_Ground_Vehicles\data\Scorpion\V_M808_FRO_CO.paa"
      , "V_FZ_Ground_Vehicles\data\Scorpion\V_M808_FRO_T_CO.paa"
      , "V_FZ_Ground_Vehicles\data\Scorpion\V_M808_FRO_D3_CO.paa"
      , "Optre_Vehicles_Tracked\Scorpion\data\texture\scorp_decals_ca.paa"
      , "Optre_Vehicles_Tracked\Scorpion\data\texture\scorp_net_wood_ca.paa"
      , "Optre_Vehicles_Tracked\Scorpion\data\texture\scorp_net_wood_ca.paa"
      , "V_FZ_Ground_Vehicles\data\Scorpion\V_M808_FRO_MR_CO.paa"
      , "V_FZ_Ground_Vehicles\data\Oryx\V_M494_FRO_MG_CO.paa"
    };
  };
  class VES_Tundra {
    textures[] = {
      "V_FZ_Ground_Vehicles\data\Scorpion\V_M808_TUN_CO.paa"
      , "V_FZ_Ground_Vehicles\data\Scorpion\V_M808_TUN_T_CO.paa"
      , "V_FZ_Ground_Vehicles\data\Scorpion\V_M808_TUN_D3_CO.paa"
      , "Optre_Vehicles_Tracked\Scorpion\data\texture\scorp_decals_ca.paa"
      , "Optre_Vehicles_Tracked\Scorpion\data\texture\scorp_net_wood_ca.paa"
      , "Optre_Vehicles_Tracked\Scorpion\data\texture\scorp_net_wood_ca.paa"
      , "V_FZ_Ground_Vehicles\data\Scorpion\V_M808_TUN_MR_CO.paa"
      , "V_FZ_Ground_Vehicles\data\Oryx\V_M494_TUN_MG_CO.paa"
    };
  };
  class VES_Dunes {
    textures[] = {
      "V_FZ_Ground_Vehicles\data\Scorpion\V_M808_DUN_CO.paa"
      , "V_FZ_Ground_Vehicles\data\Scorpion\V_M808_DUN_T_CO.paa"
      , "V_FZ_Ground_Vehicles\data\Scorpion\V_M808_DUN_D3_CO.paa"
      , "Optre_Vehicles_Tracked\Scorpion\data\texture\scorp_decals_ca.paa"
      , "Optre_Vehicles_Tracked\Scorpion\data\texture\scorp_net_wood_ca.paa"
      , "Optre_Vehicles_Tracked\Scorpion\data\texture\scorp_net_wood_ca.paa"
      , "V_FZ_Ground_Vehicles\data\Scorpion\V_M808_DUN_MR_CO.paa"
      , "V_FZ_Ground_Vehicles\data\Oryx\V_M494_DUN_MG_CO.paa"
    };
  };
  class VES_Classic {
    textures[] = {
      "V_FZ_Ground_Vehicles\data\Scorpion\V_M808_CLS_CO.paa"
      , "V_FZ_Ground_Vehicles\data\Scorpion\V_M808_CLS_T_CO.paa"
      , "V_FZ_Ground_Vehicles\data\Scorpion\V_M808_CLS_D3_CO.paa"
      , "Optre_Vehicles_Tracked\Scorpion\data\texture\scorp_decals_ca.paa"
      , "Optre_Vehicles_Tracked\Scorpion\data\texture\scorp_net_wood_ca.paa"
      , "Optre_Vehicles_Tracked\Scorpion\data\texture\scorp_net_wood_ca.paa"
      , "V_FZ_Ground_Vehicles\data\Scorpion\V_M808_CLS_MR_CO.paa"
      , "V_FZ_Ground_Vehicles\data\Oryx\V_M494_CLS_MG_CO.paa"
    };
  };
  class VES_Olive {
    textures[] = {
      "V_FZ_Ground_Vehicles\data\Scorpion\V_M808_OD3_CO.paa"
      , "V_FZ_Ground_Vehicles\data\Scorpion\V_M808_OD3_T_CO.paa"
      , "V_FZ_Ground_Vehicles\data\Scorpion\V_M808_OD3_D3_CO.paa"
      , "Optre_Vehicles_Tracked\Scorpion\data\texture\scorp_decals_ca.paa"
      , "Optre_Vehicles_Tracked\Scorpion\data\texture\scorp_net_wood_ca.paa"
      , "Optre_Vehicles_Tracked\Scorpion\data\texture\scorp_net_wood_ca.paa"
      , "V_FZ_Ground_Vehicles\data\Scorpion\V_M808_OD3_MR_CO.paa"
      , "V_FZ_Ground_Vehicles\data\Oryx\V_M494_OD3_MG_CO.paa"
    };
  };
};
