class CfgMagazineWells
{
  class UGL_40x36 {
    SUBGVAR(Magazines)[] = {
      "SWS_Magazine_3Rnd_FlareSmoke_Blue",
      "SWS_Magazine_3Rnd_FlareSmoke_Green",
      "SWS_Magazine_3Rnd_FlareSmoke_Orange",
      "SWS_Magazine_3Rnd_FlareSmoke_Purple",
      "SWS_Magazine_3Rnd_FlareSmoke_Red",
      "SWS_Magazine_3Rnd_FlareSmoke_Yellow",
      "3Rnd_Smoke_Grenade_Shell",
      "3Rnd_SmokeGreen_Grenade_Shell",
      "3Rnd_SmokeOrange_Grenade_Shell",
      "3Rnd_SmokePurple_Grenade_Shell",
      "3Rnd_SmokeRed_Grenade_Shell",
      "3Rnd_SmokeYellow_Grenade_Shell",
      "3Rnd_SmokeBlue_Grenade_Shell",
      "3Rnd_UGL_FlareGreen_F",
      "3Rnd_UGL_FlareCIR_F",
      "3Rnd_UGL_FlareRed_F",
      "3Rnd_UGL_FlareWhite_F",
      "3Rnd_UGL_FlareYellow_F"
    };
  };

  class 3UGL_40x36 {
    SUBGVAR(Magazines)[] = {
      "SWS_Magazine_3Rnd_FlareSmoke_Blue",
      "SWS_Magazine_3Rnd_FlareSmoke_Green",
      "SWS_Magazine_3Rnd_FlareSmoke_Orange",
      "SWS_Magazine_3Rnd_FlareSmoke_Purple",
      "SWS_Magazine_3Rnd_FlareSmoke_Red",
      "SWS_Magazine_3Rnd_FlareSmoke_Yellow",
      "3Rnd_Smoke_Grenade_Shell",
      "3Rnd_SmokeGreen_Grenade_Shell",
      "3Rnd_SmokeOrange_Grenade_Shell",
      "3Rnd_SmokePurple_Grenade_Shell",
      "3Rnd_SmokeRed_Grenade_Shell",
      "3Rnd_SmokeYellow_Grenade_Shell",
      "3Rnd_SmokeBlue_Grenade_Shell",
      "3Rnd_UGL_FlareGreen_F",
      "3Rnd_UGL_FlareCIR_F",
      "3Rnd_UGL_FlareRed_F",
      "3Rnd_UGL_FlareWhite_F",
      "3Rnd_UGL_FlareYellow_F"
    };
  };
};
