class CfgMagazineWells
{
  class 3UGL_40x36 {
    SUBGVAR(Magazines)[] = {
      "SWS_Magazine_3Rnd_FlareSmoke_Blue"
      , "SWS_Magazine_3Rnd_FlareSmoke_Green"
      , "SWS_Magazine_3Rnd_FlareSmoke_Orange"
      , "SWS_Magazine_3Rnd_FlareSmoke_Purple"
      , "SWS_Magazine_3Rnd_FlareSmoke_Red"
      , "SWS_Magazine_3Rnd_FlareSmoke_Yellow"
    };
  };

  class CBA_40mm_3GL
  {
    SUBGVAR(Magazines)[] = {
      "SWS_Magazine_3Rnd_FlareSmoke_Blue"
      , "SWS_Magazine_3Rnd_FlareSmoke_Green"
      , "SWS_Magazine_3Rnd_FlareSmoke_Orange"
      , "SWS_Magazine_3Rnd_FlareSmoke_Purple"
      , "SWS_Magazine_3Rnd_FlareSmoke_Red"
      , "SWS_Magazine_3Rnd_FlareSmoke_Yellow"
    };
  };
};
