#define PLOW_MOVING 		"plowMoving"
#define PLOW_UP 			"plowUp"
#define PLOW_NONE           "plowNone"
#define PLOW_VEHICLE_TRENCH "plowVehicleTrench"
#define PLOW_GIANT_TRENCH	"plowGiantTrench"
#define PLOW_LONG_TRENCH	"plowLongTrench"