//////////////////////////////////////////////////////////////////////////////////
// Config Automatically Generated by ALiVE ORBAT Creator
// Generated with Arma 3 version 216.151618 on Stable branch
// Generated with ALiVE version 2.1.2.2309211
//////////////////////////////////////////////////////////////////////////////////


class CBA_Extended_EventHandlers_base;

class CfgVehicles {

    class EMP_CBRN_Element_Lead;
    class EMP_CBRN_Element_Lead_OCimport_01 : EMP_CBRN_Element_Lead { scope = 0; class EventHandlers; };
    class EMP_CBRN_Element_Lead_OCimport_02 : EMP_CBRN_Element_Lead_OCimport_01 { class EventHandlers; };

    class I_APC_tracked_03_cannon_F;
    class I_APC_tracked_03_cannon_F_OCimport_01 : I_APC_tracked_03_cannon_F { scope = 0; class EventHandlers; class Turrets; };
    class I_APC_tracked_03_cannon_F_OCimport_02 : I_APC_tracked_03_cannon_F_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class MainTurret;
        };
    };

    class EMP_Polaris_DAGOR_HMG;
    class EMP_Polaris_DAGOR_HMG_OCimport_01 : EMP_Polaris_DAGOR_HMG { scope = 0; class EventHandlers; class Turrets; };
    class EMP_Polaris_DAGOR_HMG_OCimport_02 : EMP_Polaris_DAGOR_HMG_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class TopTurret;
            class CodRiverTurret;
            class CargoTurret_02;
            class CargoTurret_03;
        };
    };

    class I_C_Offroad_02_LMG_F;
    class I_C_Offroad_02_LMG_F_OCimport_01 : I_C_Offroad_02_LMG_F { scope = 0; class EventHandlers; class Turrets; };
    class I_C_Offroad_02_LMG_F_OCimport_02 : I_C_Offroad_02_LMG_F_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class LMG_Turret;
            class CargoTurret_01;
        };
    };

    class O_Truck_02_covered_F;
    class O_Truck_02_covered_F_OCimport_01 : O_Truck_02_covered_F { scope = 0; class EventHandlers; class Turrets; };
    class O_Truck_02_covered_F_OCimport_02 : O_Truck_02_covered_F_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class CargoTurret_01;
            class CargoTurret_02;
        };
    };


    class O_URArmy_Squad_Lead_01 : EMP_CBRN_Element_Lead_OCimport_02 {
        author = "Rabbit";
        scope = 2;
        scopeCurator = 2;
        displayName = "Squad Lead";
        side = 0;
        faction = "O_URArmy";

        identityTypes[] = {"Head_Greek","LanguageGRE_F","G_HAF_default"};

        uniformClass = "U_C_CBRN_Suit_01_Blue_F";

        linkedItems[] = {"V_PlateCarrier1_blk","H_PASGT_basic_black_F","ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch","OPTRE_NVG_UA_HURS_CNM"};
        respawnlinkedItems[] = {"V_PlateCarrier1_blk","H_PASGT_basic_black_F","ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch","OPTRE_NVG_UA_HURS_CNM"};

        weapons[] = {"arifle_AK12_F","EMP_hgun_Pistol_heavy_01_F_acc_flashlight_pistol","Laserdesignator_01_khk_F"};
        respawnWeapons[] = {"arifle_AK12_F","EMP_hgun_Pistol_heavy_01_F_acc_flashlight_pistol","Laserdesignator_01_khk_F"};

        magazines[] = {"30Rnd_762x39_AK12_Mag_F","11Rnd_45ACP_Mag","Laserbatteries","30Rnd_762x39_AK12_Mag_F","11Rnd_45ACP_Mag","Laserbatteries"};
        respawnMagazines[] = {"30Rnd_762x39_AK12_Mag_F","11Rnd_45ACP_Mag","Laserbatteries","30Rnd_762x39_AK12_Mag_F","11Rnd_45ACP_Mag","Laserbatteries"};

        backpack = "B_RadioBag_01_black_F";

        ALiVE_orbatCreator_loadout[] = {{"arifle_AK12_F","","acc_flashlight","optic_MRCO",{"30Rnd_762x39_AK12_Mag_F",30},{},""},{},{"EMP_hgun_Pistol_heavy_01_F_acc_flashlight_pistol","","acc_flashlight_pistol","",{"11Rnd_45ACP_Mag",15},{},""},{"U_C_CBRN_Suit_01_Blue_F",{{"FirstAidKit",3},{"WNZ_EMPGrenade",1,1},{"HandGrenade",1,1}}},{"V_PlateCarrier1_blk",{{"ACE_bloodIV_500",1},{"ACE_quikclot",5},{"11Rnd_45ACP_Mag",1,15},{"HandGrenade",2,1},{"OPTRE_M2_Smoke",2,1},{"30Rnd_762x39_AK12_Mag_F",3,30}}},{"B_RadioBag_01_black_F",{}},"H_PASGT_basic_black_F","G_CBRN_M04_Hood",{"Laserdesignator_01_khk_F","","","",{"Laserbatteries",1},{},""},{"ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch","OPTRE_NVG_UA_HURS_CNM"}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_URArmy_Team_Lead_01 : O_URArmy_Squad_Lead_01 {
        author = "Rabbit";
        scope = 2;
        scopeCurator = 2;
        displayName = "Team Lead";
        side = 0;
        faction = "O_URArmy";

        identityTypes[] = {"Head_Greek","LanguageGRE_F","G_HAF_default"};

        uniformClass = "U_C_CBRN_Suit_01_Blue_F";

        linkedItems[] = {"V_PlateCarrier1_blk","H_PASGT_basic_black_F","ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch","OPTRE_NVG_UA_HURS_CNM"};
        respawnlinkedItems[] = {"V_PlateCarrier1_blk","H_PASGT_basic_black_F","ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch","OPTRE_NVG_UA_HURS_CNM"};

        weapons[] = {"arifle_AK12_GL_F","EMP_hgun_Pistol_heavy_01_F_acc_flashlight_pistol","Laserdesignator_01_khk_F"};
        respawnWeapons[] = {"arifle_AK12_GL_F","EMP_hgun_Pistol_heavy_01_F_acc_flashlight_pistol","Laserdesignator_01_khk_F"};

        magazines[] = {"30Rnd_762x39_AK12_Mag_F","1Rnd_HE_Grenade_shell","11Rnd_45ACP_Mag","Laserbatteries","30Rnd_762x39_AK12_Mag_F","1Rnd_HE_Grenade_shell","11Rnd_45ACP_Mag","Laserbatteries"};
        respawnMagazines[] = {"30Rnd_762x39_AK12_Mag_F","1Rnd_HE_Grenade_shell","11Rnd_45ACP_Mag","Laserbatteries","30Rnd_762x39_AK12_Mag_F","1Rnd_HE_Grenade_shell","11Rnd_45ACP_Mag","Laserbatteries"};

        backpack = "B_RadioBag_01_black_F";

        ALiVE_orbatCreator_loadout[] = {{"arifle_AK12_GL_F","","acc_flashlight","optic_MRCO",{"30Rnd_762x39_AK12_Mag_F",30},{"1Rnd_HE_Grenade_shell",1},""},{},{"EMP_hgun_Pistol_heavy_01_F_acc_flashlight_pistol","","acc_flashlight_pistol","",{"11Rnd_45ACP_Mag",15},{},""},{"U_C_CBRN_Suit_01_Blue_F",{{"FirstAidKit",3},{"WNZ_EMPGrenade",1,1},{"HandGrenade",1,1}}},{"V_PlateCarrier1_blk",{{"ACE_quikclot",5},{"ACE_bloodIV_500",1},{"11Rnd_45ACP_Mag",1,15},{"HandGrenade",2,1},{"OPTRE_M2_Smoke",2,1},{"30Rnd_762x39_AK12_Mag_F",3,30},{"1Rnd_HE_Grenade_shell",3,1}}},{"B_RadioBag_01_black_F",{}},"H_PASGT_basic_black_F","G_CBRN_M04_Hood",{"Laserdesignator_01_khk_F","","","",{"Laserbatteries",1},{},""},{"ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch","OPTRE_NVG_UA_HURS_CNM"}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_URArmy_Rifleperson_1_01 : O_URArmy_Team_Lead_01 {
        author = "Rabbit";
        scope = 2;
        scopeCurator = 2;
        displayName = "Rifleperson 1";
        side = 0;
        faction = "O_URArmy";

        identityTypes[] = {"Head_Greek","LanguageGRE_F","G_HAF_default"};

        uniformClass = "U_C_CBRN_Suit_01_Blue_F";

        linkedItems[] = {"OPTRE_Vest_CMA_Heavy","H_PASGT_basic_black_F","ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch","OPTRE_NVG_UAB_UL_CNM"};
        respawnlinkedItems[] = {"OPTRE_Vest_CMA_Heavy","H_PASGT_basic_black_F","ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch","OPTRE_NVG_UAB_UL_CNM"};

        weapons[] = {"arifle_AK12_F","EMP_hgun_Pistol_heavy_01_F_acc_flashlight_pistol","Laserdesignator_01_khk_F"};
        respawnWeapons[] = {"arifle_AK12_F","EMP_hgun_Pistol_heavy_01_F_acc_flashlight_pistol","Laserdesignator_01_khk_F"};

        magazines[] = {"30Rnd_762x39_AK12_Mag_F","11Rnd_45ACP_Mag","Laserbatteries","30Rnd_762x39_AK12_Mag_F","11Rnd_45ACP_Mag","Laserbatteries"};
        respawnMagazines[] = {"30Rnd_762x39_AK12_Mag_F","11Rnd_45ACP_Mag","Laserbatteries","30Rnd_762x39_AK12_Mag_F","11Rnd_45ACP_Mag","Laserbatteries"};

        backpack = "B_CombinationUnitRespirator_01_F";

        ALiVE_orbatCreator_loadout[] = {{"arifle_AK12_F","","acc_flashlight","ACE_optic_Hamr_PIP",{"30Rnd_762x39_AK12_Mag_F",30},{},""},{},{"EMP_hgun_Pistol_heavy_01_F_acc_flashlight_pistol","","acc_flashlight_pistol","",{"11Rnd_45ACP_Mag",15},{},""},{"U_C_CBRN_Suit_01_Blue_F",{{"FirstAidKit",3},{"WNZ_EMPGrenade",1,1},{"HandGrenade",1,1}}},{"OPTRE_Vest_CMA_Heavy",{{"ACE_bloodIV_500",2},{"ACE_quikclot",10},{"11Rnd_45ACP_Mag",1,15},{"HandGrenade",2,1},{"30Rnd_762x39_AK12_Mag_F",4,30}}},{"B_CombinationUnitRespirator_01_F",{}},"H_PASGT_basic_black_F","G_CBRN_M04_Hood",{"Laserdesignator_01_khk_F","","","",{"Laserbatteries",1},{},""},{"ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch","OPTRE_NVG_UAB_UL_CNM"}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_URArmy_Rifleperson_2_01 : O_URArmy_Rifleperson_1_01 {
        author = "Rabbit";
        scope = 2;
        scopeCurator = 2;
        displayName = "Rifleperson 2";
        side = 0;
        faction = "O_URArmy";

        identityTypes[] = {"Head_Greek","LanguageGRE_F","G_HAF_default"};

        uniformClass = "U_C_CBRN_Suit_01_Blue_F";

        linkedItems[] = {"OPTRE_Vest_CMA_Heavy","H_PASGT_basic_black_F","ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch","OPTRE_NVG_UAB_UL_CNM"};
        respawnlinkedItems[] = {"OPTRE_Vest_CMA_Heavy","H_PASGT_basic_black_F","ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch","OPTRE_NVG_UAB_UL_CNM"};

        weapons[] = {"OPTRE_MA37K","EMP_hgun_Pistol_heavy_01_F_acc_flashlight_pistol","Laserdesignator_01_khk_F"};
        respawnWeapons[] = {"OPTRE_MA37K","EMP_hgun_Pistol_heavy_01_F_acc_flashlight_pistol","Laserdesignator_01_khk_F"};

        magazines[] = {"OPTRE_32Rnd_762x51_Mag","11Rnd_45ACP_Mag","Laserbatteries","OPTRE_32Rnd_762x51_Mag","11Rnd_45ACP_Mag","Laserbatteries"};
        respawnMagazines[] = {"OPTRE_32Rnd_762x51_Mag","11Rnd_45ACP_Mag","Laserbatteries","OPTRE_32Rnd_762x51_Mag","11Rnd_45ACP_Mag","Laserbatteries"};

        backpack = "B_CombinationUnitRespirator_01_F";

        ALiVE_orbatCreator_loadout[] = {{"OPTRE_MA37K","","OPTRE_M12_Laser","OPTRE_M12_Optic_Red",{"OPTRE_32Rnd_762x51_Mag",32},{},""},{},{"EMP_hgun_Pistol_heavy_01_F_acc_flashlight_pistol","","acc_flashlight_pistol","",{"11Rnd_45ACP_Mag",15},{},""},{"U_C_CBRN_Suit_01_Blue_F",{{"FirstAidKit",3},{"WNZ_EMPGrenade",1,1},{"HandGrenade",1,1}}},{"OPTRE_Vest_CMA_Heavy",{{"ACE_bloodIV_500",1},{"ACE_quikclot",10},{"11Rnd_45ACP_Mag",1,15},{"HandGrenade",2,1},{"OPTRE_32Rnd_762x51_Mag",4,32}}},{"B_CombinationUnitRespirator_01_F",{}},"H_PASGT_basic_black_F","G_CBRN_M04_Hood",{"Laserdesignator_01_khk_F","","","",{"Laserbatteries",1},{},""},{"ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch","OPTRE_NVG_UAB_UL_CNM"}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_URArmy_Automatic_Rifle_01 : O_URArmy_Rifleperson_2_01 {
        author = "Rabbit";
        scope = 2;
        scopeCurator = 2;
        displayName = "Automatic Rifle";
        side = 0;
        faction = "O_URArmy";

        identityTypes[] = {"Head_Greek","LanguageGRE_F","G_HAF_default"};

        uniformClass = "U_C_CBRN_Suit_01_Blue_F";

        linkedItems[] = {"V_PlateCarrier1_blk","H_PASGT_basic_black_F","ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch","OPTRE_NVG_UA_UL_CNM"};
        respawnlinkedItems[] = {"V_PlateCarrier1_blk","H_PASGT_basic_black_F","ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch","OPTRE_NVG_UA_UL_CNM"};

        weapons[] = {"MMG_02_black_F","EMP_hgun_Pistol_heavy_01_F_acc_flashlight_pistol","Laserdesignator_01_khk_F"};
        respawnWeapons[] = {"MMG_02_black_F","EMP_hgun_Pistol_heavy_01_F_acc_flashlight_pistol","Laserdesignator_01_khk_F"};

        magazines[] = {"130Rnd_338_Mag","11Rnd_45ACP_Mag","Laserbatteries","130Rnd_338_Mag","11Rnd_45ACP_Mag","Laserbatteries"};
        respawnMagazines[] = {"130Rnd_338_Mag","11Rnd_45ACP_Mag","Laserbatteries","130Rnd_338_Mag","11Rnd_45ACP_Mag","Laserbatteries"};

        backpack = "B_Carryall_blk";

        ALiVE_orbatCreator_loadout[] = {{"MMG_02_black_F","","","optic_ERCO_blk_F",{"130Rnd_338_Mag",130},{},"bipod_01_F_blk"},{},{"EMP_hgun_Pistol_heavy_01_F_acc_flashlight_pistol","","acc_flashlight_pistol","",{"11Rnd_45ACP_Mag",15},{},""},{"U_C_CBRN_Suit_01_Blue_F",{{"FirstAidKit",3},{"WNZ_EMPGrenade",1,1},{"HandGrenade",1,1}}},{"V_PlateCarrier1_blk",{{"ACE_bloodIV_500",1},{"ACE_quikclot",5},{"11Rnd_45ACP_Mag",1,15},{"HandGrenade",2,1},{"130Rnd_338_Mag",1,130}}},{"B_Carryall_blk",{{"130Rnd_338_Mag",2,130}}},"H_PASGT_basic_black_F","G_CBRN_M04_Hood",{"Laserdesignator_01_khk_F","","","",{"Laserbatteries",1},{},""},{"ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch","OPTRE_NVG_UA_UL_CNM"}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_URArmy_Medic_01 : O_URArmy_Rifleperson_2_01 {
        author = "Rabbit";
        scope = 2;
        scopeCurator = 2;
        displayName = "Medic";
        side = 0;
        faction = "O_URArmy";

        identityTypes[] = {"Head_Greek","LanguageGRE_F","G_HAF_default"};

        uniformClass = "U_C_CBRN_Suit_01_Blue_F";

        linkedItems[] = {"OPTRE_Vest_CMA_Light","H_PASGT_basic_white_F","ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch","OPTRE_NVG_UA_UL_CNM"};
        respawnlinkedItems[] = {"OPTRE_Vest_CMA_Light","H_PASGT_basic_white_F","ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch","OPTRE_NVG_UA_UL_CNM"};

        weapons[] = {"OPTRE_MA37K","EMP_hgun_Pistol_heavy_01_F_acc_flashlight_pistol","Laserdesignator_01_khk_F"};
        respawnWeapons[] = {"OPTRE_MA37K","EMP_hgun_Pistol_heavy_01_F_acc_flashlight_pistol","Laserdesignator_01_khk_F"};

        magazines[] = {"OPTRE_32Rnd_762x51_Mag","11Rnd_45ACP_Mag","Laserbatteries","OPTRE_32Rnd_762x51_Mag","11Rnd_45ACP_Mag","Laserbatteries"};
        respawnMagazines[] = {"OPTRE_32Rnd_762x51_Mag","11Rnd_45ACP_Mag","Laserbatteries","OPTRE_32Rnd_762x51_Mag","11Rnd_45ACP_Mag","Laserbatteries"};

        backpack = "B_CombinationUnitRespirator_01_F";

        ALiVE_orbatCreator_loadout[] = {{"OPTRE_MA37K","","OPTRE_M12_Laser","OPTRE_M12_Optic_Red",{"OPTRE_32Rnd_762x51_Mag",32},{},""},{},{"EMP_hgun_Pistol_heavy_01_F_acc_flashlight_pistol","","acc_flashlight_pistol","",{"11Rnd_45ACP_Mag",15},{},""},{"U_C_CBRN_Suit_01_Blue_F",{{"FirstAidKit",3},{"WNZ_EMPGrenade",1,1},{"HandGrenade",1,1}}},{"OPTRE_Vest_CMA_Light",{{"ACE_bloodIV_500",4},{"ACE_quikclot",20},{"11Rnd_45ACP_Mag",1,15},{"HandGrenade",2,1},{"OPTRE_32Rnd_762x51_Mag",4,32}}},{"B_CombinationUnitRespirator_01_F",{}},"H_PASGT_basic_white_F","G_CBRN_M04_Hood",{"Laserdesignator_01_khk_F","","","",{"Laserbatteries",1},{},""},{"ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch","OPTRE_NVG_UA_UL_CNM"}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_URArmy_Marksman_01 : O_URArmy_Automatic_Rifle_01 {
        author = "Rabbit";
        scope = 2;
        scopeCurator = 2;
        displayName = "Marksman";
        side = 0;
        faction = "O_URArmy";

        identityTypes[] = {"Head_Greek","LanguageGRE_F","G_HAF_default"};

        uniformClass = "U_C_CBRN_Suit_01_Blue_F";

        linkedItems[] = {"V_PlateCarrier1_blk","H_PASGT_basic_black_F","ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch","OPTRE_NVG_UA_UL_CNM"};
        respawnlinkedItems[] = {"V_PlateCarrier1_blk","H_PASGT_basic_black_F","ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch","OPTRE_NVG_UA_UL_CNM"};

        weapons[] = {"srifle_DMR_02_F","EMP_hgun_Pistol_heavy_01_F_acc_flashlight_pistol","Laserdesignator_01_khk_F"};
        respawnWeapons[] = {"srifle_DMR_02_F","EMP_hgun_Pistol_heavy_01_F_acc_flashlight_pistol","Laserdesignator_01_khk_F"};

        magazines[] = {"10Rnd_338_Mag","11Rnd_45ACP_Mag","Laserbatteries","10Rnd_338_Mag","11Rnd_45ACP_Mag","Laserbatteries"};
        respawnMagazines[] = {"10Rnd_338_Mag","11Rnd_45ACP_Mag","Laserbatteries","10Rnd_338_Mag","11Rnd_45ACP_Mag","Laserbatteries"};

        backpack = "B_Carryall_blk";

        ALiVE_orbatCreator_loadout[] = {{"srifle_DMR_02_F","","","optic_AMS",{"10Rnd_338_Mag",10},{},""},{},{"EMP_hgun_Pistol_heavy_01_F_acc_flashlight_pistol","","acc_flashlight_pistol","",{"11Rnd_45ACP_Mag",15},{},""},{"U_C_CBRN_Suit_01_Blue_F",{{"FirstAidKit",3},{"WNZ_EMPGrenade",1,1},{"HandGrenade",1,1}}},{"V_PlateCarrier1_blk",{{"ACE_bloodIV_500",1},{"ACE_quikclot",5},{"11Rnd_45ACP_Mag",1,15},{"HandGrenade",2,1},{"ACE_10Rnd_338_API526_Mag",2,10},{"ACE_10Rnd_338_300gr_HPBT_Mag",2,10},{"ACE_10Rnd_762x67_Mk248_Mod_1_Mag",1,10}}},{"B_Carryall_blk",{}},"H_PASGT_basic_black_F","G_CBRN_M04_Hood",{"Laserdesignator_01_khk_F","","","",{"Laserbatteries",1},{},""},{"ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch","OPTRE_NVG_UA_UL_CNM"}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_URArmy_Crew_01 : O_URArmy_Rifleperson_1_01 {
        author = "Rabbit";
        scope = 2;
        scopeCurator = 2;
        displayName = "Crew";
        side = 0;
        faction = "O_URArmy";

        identityTypes[] = {"Head_Greek","LanguageGRE_F","G_HAF_default"};

        uniformClass = "U_C_CBRN_Suit_01_Blue_F";

        linkedItems[] = {"OPTRE_Vest_CMA_Light","H_PilotHelmetFighter_B","ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"OPTRE_Vest_CMA_Light","H_PilotHelmetFighter_B","ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch"};

        weapons[] = {"hgun_PDW2000_F","EMP_hgun_Pistol_heavy_01_F_acc_flashlight_pistol","Laserdesignator_01_khk_F"};
        respawnWeapons[] = {"hgun_PDW2000_F","EMP_hgun_Pistol_heavy_01_F_acc_flashlight_pistol","Laserdesignator_01_khk_F"};

        magazines[] = {"30Rnd_9x21_Mag","11Rnd_45ACP_Mag","Laserbatteries","30Rnd_9x21_Mag","11Rnd_45ACP_Mag","Laserbatteries"};
        respawnMagazines[] = {"30Rnd_9x21_Mag","11Rnd_45ACP_Mag","Laserbatteries","30Rnd_9x21_Mag","11Rnd_45ACP_Mag","Laserbatteries"};

        backpack = "B_CombinationUnitRespirator_01_F";

        ALiVE_orbatCreator_loadout[] = {{"hgun_PDW2000_F","","","optic_Holosight_blk_F",{"30Rnd_9x21_Mag",30},{},""},{},{"EMP_hgun_Pistol_heavy_01_F_acc_flashlight_pistol","","acc_flashlight_pistol","",{"11Rnd_45ACP_Mag",15},{},""},{"U_C_CBRN_Suit_01_Blue_F",{{"FirstAidKit",3},{"WNZ_EMPGrenade",1,1},{"HandGrenade",1,1}}},{"OPTRE_Vest_CMA_Light",{{"ACE_bloodIV_500",2},{"ACE_quikclot",10},{"11Rnd_45ACP_Mag",1,15},{"HandGrenade",2,1},{"30Rnd_9x21_Red_Mag",4,30}}},{"B_CombinationUnitRespirator_01_F",{}},"H_PilotHelmetFighter_B","",{"Laserdesignator_01_khk_F","","","",{"Laserbatteries",1},{},""},{"ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_URArmy_Sniper_01 : O_URArmy_Marksman_01 {
        author = "Rabbit";
        scope = 2;
        scopeCurator = 2;
        displayName = "Sniper";
        side = 0;
        faction = "O_URArmy";

        identityTypes[] = {"Head_Greek","LanguageGRE_F","G_HAF_default"};

        uniformClass = "U_B_CBRN_Suit_01_MTP_F";

        linkedItems[] = {"V_PlateCarrier2_rgr_noflag_F","H_HelmetIA","ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch","OPTRE_NVG_UA_UL_CNM"};
        respawnlinkedItems[] = {"V_PlateCarrier2_rgr_noflag_F","H_HelmetIA","ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch","OPTRE_NVG_UA_UL_CNM"};

        weapons[] = {"srifle_GM6_ghex_F","EMP_hgun_Pistol_heavy_01_F_acc_flashlight_pistol","Laserdesignator_01_khk_F"};
        respawnWeapons[] = {"srifle_GM6_ghex_F","EMP_hgun_Pistol_heavy_01_F_acc_flashlight_pistol","Laserdesignator_01_khk_F"};

        magazines[] = {"5Rnd_127x108_Mag","11Rnd_45ACP_Mag","Laserbatteries","5Rnd_127x108_Mag","11Rnd_45ACP_Mag","Laserbatteries"};
        respawnMagazines[] = {"5Rnd_127x108_Mag","11Rnd_45ACP_Mag","Laserbatteries","5Rnd_127x108_Mag","11Rnd_45ACP_Mag","Laserbatteries"};

        backpack = "B_RadioBag_01_digi_F";

        ALiVE_orbatCreator_loadout[] = {{"srifle_GM6_ghex_F","","","optic_AMS_khk",{"5Rnd_127x108_Mag",5},{},""},{},{"EMP_hgun_Pistol_heavy_01_F_acc_flashlight_pistol","","acc_flashlight_pistol","",{"11Rnd_45ACP_Mag",15},{},""},{"U_B_CBRN_Suit_01_MTP_F",{{"FirstAidKit",3},{"WNZ_EMPGrenade",1,1},{"HandGrenade",1,1}}},{"V_PlateCarrier2_rgr_noflag_F",{{"ACE_bloodIV_500",1},{"ACE_quikclot",5},{"11Rnd_45ACP_Mag",1,15},{"HandGrenade",2,1},{"5Rnd_127x108_APDS_Mag",6,5}}},{"B_RadioBag_01_digi_F",{}},"H_HelmetIA","G_Balaclava_TI_G_tna_F",{"Laserdesignator_01_khk_F","","","",{"Laserbatteries",1},{},""},{"ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch","OPTRE_NVG_UA_UL_CNM"}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_URArmy_Spotter_01 : O_URArmy_Sniper_01 {
        author = "Rabbit";
        scope = 2;
        scopeCurator = 2;
        displayName = "Spotter";
        side = 0;
        faction = "O_URArmy";

        identityTypes[] = {"Head_Greek","LanguageGRE_F","G_HAF_default"};

        uniformClass = "U_B_CBRN_Suit_01_MTP_F";

        linkedItems[] = {"V_PlateCarrier2_rgr_noflag_F","H_HelmetIA","ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch","OPTRE_NVG_UA_UL_CNM"};
        respawnlinkedItems[] = {"V_PlateCarrier2_rgr_noflag_F","H_HelmetIA","ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch","OPTRE_NVG_UA_UL_CNM"};

        weapons[] = {"arifle_AK12_lush_F","EMP_hgun_Pistol_heavy_01_F_acc_flashlight_pistol","Laserdesignator_01_khk_F"};
        respawnWeapons[] = {"arifle_AK12_lush_F","EMP_hgun_Pistol_heavy_01_F_acc_flashlight_pistol","Laserdesignator_01_khk_F"};

        magazines[] = {"30rnd_762x39_AK12_Lush_Mag_F","11Rnd_45ACP_Mag","Laserbatteries","30rnd_762x39_AK12_Lush_Mag_F","11Rnd_45ACP_Mag","Laserbatteries"};
        respawnMagazines[] = {"30rnd_762x39_AK12_Lush_Mag_F","11Rnd_45ACP_Mag","Laserbatteries","30rnd_762x39_AK12_Lush_Mag_F","11Rnd_45ACP_Mag","Laserbatteries"};

        backpack = "B_TacticalPack_oli";

        ALiVE_orbatCreator_loadout[] = {{"arifle_AK12_lush_F","","","optic_Arco_ghex_F",{"30rnd_762x39_AK12_Lush_Mag_F",30},{},""},{},{"EMP_hgun_Pistol_heavy_01_F_acc_flashlight_pistol","","acc_flashlight_pistol","",{"11Rnd_45ACP_Mag",15},{},""},{"U_B_CBRN_Suit_01_MTP_F",{{"FirstAidKit",3},{"WNZ_EMPGrenade",1,1},{"HandGrenade",1,1}}},{"V_PlateCarrier2_rgr_noflag_F",{{"ACE_bloodIV_500",1},{"ACE_quikclot",5},{"11Rnd_45ACP_Mag",1,15},{"HandGrenade",2,1},{"30rnd_762x39_AK12_Lush_Mag_F",3,30}}},{"B_TacticalPack_oli",{}},"H_HelmetIA","G_Balaclava_TI_G_tna_F",{"Laserdesignator_01_khk_F","","","",{"Laserbatteries",1},{},""},{"ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch","OPTRE_NVG_UA_UL_CNM"}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_URArmy_Marine_1_01 : O_URArmy_Rifleperson_1_01 {
        author = "Rabbit";
        scope = 2;
        scopeCurator = 2;
        displayName = "Marine 1";
        side = 0;
        faction = "O_URArmy";

        identityTypes[] = {"Head_Greek","LanguageGRE_F","G_HAF_default"};

        uniformClass = "U_C_CBRN_Suit_01_White_F";

        linkedItems[] = {"OPTRE_Vest_CMA_Heavy","H_PASGT_basic_white_F","ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch","OPTRE_NVG_UAB_UL_CNM"};
        respawnlinkedItems[] = {"OPTRE_Vest_CMA_Heavy","H_PASGT_basic_white_F","ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch","OPTRE_NVG_UAB_UL_CNM"};

        weapons[] = {"arifle_AK12_F","EMP_hgun_Pistol_heavy_01_F_acc_flashlight_pistol","Laserdesignator_01_khk_F"};
        respawnWeapons[] = {"arifle_AK12_F","EMP_hgun_Pistol_heavy_01_F_acc_flashlight_pistol","Laserdesignator_01_khk_F"};

        magazines[] = {"30Rnd_762x39_AK12_Mag_F","11Rnd_45ACP_Mag","Laserbatteries","30Rnd_762x39_AK12_Mag_F","11Rnd_45ACP_Mag","Laserbatteries"};
        respawnMagazines[] = {"30Rnd_762x39_AK12_Mag_F","11Rnd_45ACP_Mag","Laserbatteries","30Rnd_762x39_AK12_Mag_F","11Rnd_45ACP_Mag","Laserbatteries"};

        backpack = "B_CombinationUnitRespirator_01_F";

        ALiVE_orbatCreator_loadout[] = {{"arifle_AK12_F","","acc_flashlight","OPTRE_M12_Optic",{"30Rnd_762x39_AK12_Mag_F",30},{},""},{},{"EMP_hgun_Pistol_heavy_01_F_acc_flashlight_pistol","","acc_flashlight_pistol","",{"11Rnd_45ACP_Mag",15},{},""},{"U_C_CBRN_Suit_01_White_F",{{"FirstAidKit",3},{"WNZ_EMPGrenade",1,1},{"HandGrenade",1,1}}},{"OPTRE_Vest_CMA_Heavy",{{"ACE_bloodIV_500",2},{"ACE_quikclot",10},{"11Rnd_45ACP_Mag",1,15},{"HandGrenade",2,1},{"30Rnd_762x39_AK12_Mag_F",4,30}}},{"B_CombinationUnitRespirator_01_F",{}},"H_PASGT_basic_white_F","G_CBRN_S10",{"Laserdesignator_01_khk_F","","","",{"Laserbatteries",1},{},""},{"ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch","OPTRE_NVG_UAB_UL_CNM"}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_URArmy_Marine_2_01 : O_URArmy_Marine_1_01 {
        author = "Rabbit";
        scope = 2;
        scopeCurator = 2;
        displayName = "Marine 2";
        side = 0;
        faction = "O_URArmy";

        identityTypes[] = {"Head_Greek","LanguageGRE_F","G_HAF_default"};

        uniformClass = "U_C_CBRN_Suit_01_White_F";

        linkedItems[] = {"OPTRE_Vest_CMA_Heavy","H_PASGT_basic_white_F","ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch","OPTRE_NVG_UAB_UL_CNM"};
        respawnlinkedItems[] = {"OPTRE_Vest_CMA_Heavy","H_PASGT_basic_white_F","ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch","OPTRE_NVG_UAB_UL_CNM"};

        weapons[] = {"OPTRE_M45ATAC","EMP_hgun_Pistol_heavy_01_F_acc_flashlight_pistol","Laserdesignator_01_khk_F"};
        respawnWeapons[] = {"OPTRE_M45ATAC","EMP_hgun_Pistol_heavy_01_F_acc_flashlight_pistol","Laserdesignator_01_khk_F"};

        magazines[] = {"OPTRE_12Rnd_8Gauge_Pellets","11Rnd_45ACP_Mag","Laserbatteries","OPTRE_12Rnd_8Gauge_Pellets","11Rnd_45ACP_Mag","Laserbatteries"};
        respawnMagazines[] = {"OPTRE_12Rnd_8Gauge_Pellets","11Rnd_45ACP_Mag","Laserbatteries","OPTRE_12Rnd_8Gauge_Pellets","11Rnd_45ACP_Mag","Laserbatteries"};

        backpack = "B_CombinationUnitRespirator_01_F";

        ALiVE_orbatCreator_loadout[] = {{"OPTRE_M45ATAC","","","OPTRE_M12_Optic",{"OPTRE_12Rnd_8Gauge_Pellets",12},{},""},{},{"EMP_hgun_Pistol_heavy_01_F_acc_flashlight_pistol","","acc_flashlight_pistol","",{"11Rnd_45ACP_Mag",15},{},""},{"U_C_CBRN_Suit_01_White_F",{{"FirstAidKit",3},{"WNZ_EMPGrenade",1,1},{"HandGrenade",1,1}}},{"OPTRE_Vest_CMA_Heavy",{{"ACE_bloodIV_500",2},{"ACE_quikclot",10},{"11Rnd_45ACP_Mag",1,15},{"HandGrenade",2,1},{"SWS_Magazine_12_Rnd_Shotgun_Incendiary",5,12}}},{"B_CombinationUnitRespirator_01_F",{}},"H_PASGT_basic_white_F","G_CBRN_S10",{"Laserdesignator_01_khk_F","","","",{"Laserbatteries",1},{},""},{"ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch","OPTRE_NVG_UAB_UL_CNM"}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_URArmy_Marine_Team_Lead_01 : O_URArmy_Marine_1_01 {
        author = "Rabbit";
        scope = 2;
        scopeCurator = 2;
        displayName = "Marine Team Lead";
        side = 0;
        faction = "O_URArmy";

        identityTypes[] = {"Head_Greek","LanguageGRE_F","G_HAF_default"};

        uniformClass = "U_C_CBRN_Suit_01_White_F";

        linkedItems[] = {"OPTRE_Vest_CMA_Heavy","H_PASGT_basic_white_F","ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch","OPTRE_NVG_UAB_UL_CNM"};
        respawnlinkedItems[] = {"OPTRE_Vest_CMA_Heavy","H_PASGT_basic_white_F","ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch","OPTRE_NVG_UAB_UL_CNM"};

        weapons[] = {"19_UNSC_M7","EMP_hgun_Pistol_heavy_01_F_acc_flashlight_pistol","Laserdesignator_01_khk_F"};
        respawnWeapons[] = {"19_UNSC_M7","EMP_hgun_Pistol_heavy_01_F_acc_flashlight_pistol","Laserdesignator_01_khk_F"};

        magazines[] = {"60Rnd_5x23_m7_fmj","11Rnd_45ACP_Mag","Laserbatteries","60Rnd_5x23_m7_fmj","11Rnd_45ACP_Mag","Laserbatteries"};
        respawnMagazines[] = {"60Rnd_5x23_m7_fmj","11Rnd_45ACP_Mag","Laserbatteries","60Rnd_5x23_m7_fmj","11Rnd_45ACP_Mag","Laserbatteries"};

        backpack = "B_RadioBag_01_oucamo_F";

        ALiVE_orbatCreator_loadout[] = {{"19_UNSC_M7","","19_UNSC_M7_LAM","19_UNSC_M7_optic",{"60Rnd_5x23_m7_fmj",60},{},""},{},{"EMP_hgun_Pistol_heavy_01_F_acc_flashlight_pistol","","acc_flashlight_pistol","",{"11Rnd_45ACP_Mag",15},{},""},{"U_C_CBRN_Suit_01_White_F",{{"FirstAidKit",3},{"WNZ_EMPGrenade",1,1},{"HandGrenade",1,1}}},{"OPTRE_Vest_CMA_Heavy",{{"ACE_bloodIV_500",2},{"ACE_quikclot",10},{"11Rnd_45ACP_Mag",1,15},{"HandGrenade",4,1},{"60Rnd_5x23_m7_fmj",4,60},{"OPTRE_M2_Smoke",2,1},{"ACE_M84",2,1}}},{"B_RadioBag_01_oucamo_F",{}},"H_PASGT_basic_white_F","G_CBRN_S10",{"Laserdesignator_01_khk_F","","","",{"Laserbatteries",1},{},""},{"ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch","OPTRE_NVG_UAB_UL_CNM"}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_URArmy_Marine_Medic_01 : O_URArmy_Marine_Team_Lead_01 {
        author = "Rabbit";
        scope = 2;
        scopeCurator = 2;
        displayName = "Marine Medic";
        side = 0;
        faction = "O_URArmy";

        identityTypes[] = {"Head_Greek","LanguageGRE_F","G_HAF_default"};

        uniformClass = "U_C_CBRN_Suit_01_White_F";

        linkedItems[] = {"OPTRE_Vest_CMA_Light","H_PASGT_basic_white_F","ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch","OPTRE_NVG_UAB_UL_CNM"};
        respawnlinkedItems[] = {"OPTRE_Vest_CMA_Light","H_PASGT_basic_white_F","ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch","OPTRE_NVG_UAB_UL_CNM"};

        weapons[] = {"19_UNSC_M7","EMP_hgun_Pistol_heavy_01_F_acc_flashlight_pistol","Laserdesignator_01_khk_F"};
        respawnWeapons[] = {"19_UNSC_M7","EMP_hgun_Pistol_heavy_01_F_acc_flashlight_pistol","Laserdesignator_01_khk_F"};

        magazines[] = {"60Rnd_5x23_m7_fmj","11Rnd_45ACP_Mag","Laserbatteries","60Rnd_5x23_m7_fmj","11Rnd_45ACP_Mag","Laserbatteries"};
        respawnMagazines[] = {"60Rnd_5x23_m7_fmj","11Rnd_45ACP_Mag","Laserbatteries","60Rnd_5x23_m7_fmj","11Rnd_45ACP_Mag","Laserbatteries"};

        backpack = "OPTRE_UNSC_Rucksack_Medic";

        ALiVE_orbatCreator_loadout[] = {{"19_UNSC_M7","","19_UNSC_M7_LAM","19_UNSC_M7_optic",{"60Rnd_5x23_m7_fmj",60},{},""},{},{"EMP_hgun_Pistol_heavy_01_F_acc_flashlight_pistol","","acc_flashlight_pistol","",{"11Rnd_45ACP_Mag",15},{},""},{"U_C_CBRN_Suit_01_White_F",{{"FirstAidKit",3},{"WNZ_EMPGrenade",1,1},{"HandGrenade",1,1}}},{"OPTRE_Vest_CMA_Light",{{"ACE_bloodIV_500",2},{"ACE_quikclot",10},{"11Rnd_45ACP_Mag",1,15},{"HandGrenade",4,1},{"60Rnd_5x23_m7_fmj",4,60},{"OPTRE_M2_Smoke",2,1},{"ACE_M84",2,1}}},{"OPTRE_UNSC_Rucksack_Medic",{}},"H_PASGT_basic_white_F","G_CBRN_S10",{"Laserdesignator_01_khk_F","","","",{"Laserbatteries",1},{},""},{"ItemMap","ItemGPS","ItemRadio","ItemCompass","ItemWatch","OPTRE_NVG_UAB_UL_CNM"}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_URArmy_Warrior_01 : I_APC_tracked_03_cannon_F_OCimport_02 {
        author = "Rabbit";
        scope = 2;
        scopeCurator = 2;
        displayName = "Warrior";
        side = 0;
        faction = "O_URArmy";
        crew = "O_URArmy_Crew_01";

        class Turrets : Turrets {
            class MainTurret : MainTurret { gunnerType = "O_URArmy_Crew_01"; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;_unit setObjectTextureGlobal [0,'A3\Armor_F_Enoch\apc_tracked_03\data\apc_tracked_03_ext_eaf_co.paa'];_unit setObjectTextureGlobal [1,'A3\Armor_F_Enoch\apc_tracked_03\data\apc_tracked_03_ext2_eaf_co.paa'];_unit setObjectTextureGlobal [2,'A3\Armor_F_Enoch\apc_tracked_03\Data\camonet_EAF_green_CO.paa'];_unit setObjectTextureGlobal [3,'A3\Armor_F_Enoch\apc_tracked_03\data\cage_EAF_CO.paa'];};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_texture = "EAF_01";

    };

    class O_URArmy_HMG_Dagger_01 : EMP_Polaris_DAGOR_HMG_OCimport_02 {
        author = "Rabbit";
        scope = 2;
        scopeCurator = 2;
        displayName = "HMG Dagger";
        side = 0;
        faction = "O_URArmy";
        crew = "O_URArmy_Team_Lead_01";

        class Turrets : Turrets {
            class TopTurret : TopTurret { gunnerType = "O_URArmy_Rifleperson_1_01"; };
            class CodRiverTurret : CodRiverTurret { gunnerType = "O_URArmy_Rifleperson_2_01"; };
            class CargoTurret_02 : CargoTurret_02 { gunnerType = ""; };
            class CargoTurret_03 : CargoTurret_03 { gunnerType = ""; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;_unit setObjectTextureGlobal [0,'\A3\Soft_F_Exp\LSV_01\Data\NATO_LSV_01_black_CO.paa'];_unit setObjectTextureGlobal [1,'\A3\Soft_F_Exp\LSV_01\Data\NATO_LSV_02_black_CO.paa'];_unit setObjectTextureGlobal [2,'\A3\Soft_F_Exp\LSV_01\Data\NATO_LSV_03_black_CO.paa'];_unit setObjectTextureGlobal [3,'\A3\Soft_F_Exp\LSV_01\Data\NATO_LSV_Adds_black_CO.paa'];_unit setObjectTextureGlobal [4,'\A3\Weapons_F_Beta\Launchers\Titan\data\launcher_INDP_co.paa'];_unit setObjectTextureGlobal [5,'\A3\Weapons_F_Beta\Launchers\Titan\data\tubem_INDP_co.paa'];};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_texture = "Black";

    };

    class O_URArmy_HMG_Jeep_01 : I_C_Offroad_02_LMG_F_OCimport_02 {
        author = "Rabbit";
        scope = 2;
        scopeCurator = 2;
        displayName = "HMG Jeep";
        side = 0;
        faction = "O_URArmy";
        crew = "O_URArmy_Team_Lead_01";

        class Turrets : Turrets {
            class LMG_Turret : LMG_Turret { gunnerType = "O_URArmy_Rifleperson_1_01"; };
            class CargoTurret_01 : CargoTurret_01 { gunnerType = ""; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;_unit setObjectTextureGlobal [0,'\A3\Soft_F_Exp\Offroad_02\Data\offroad_02_ext_olive_co.paa'];_unit setObjectTextureGlobal [1,'\A3\Soft_F_Exp\Offroad_02\Data\offroad_02_ext_olive_co.paa'];_unit setObjectTextureGlobal [2,'\A3\Soft_F_Exp\Offroad_02\Data\offroad_02_int_olive_co.paa'];_unit setObjectTextureGlobal [3,'\A3\Soft_F_Exp\Offroad_02\Data\offroad_02_int_olive_co.paa'];};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_texture = "Olive";

    };

    class O_URArmy_Covered_Truck_01 : O_Truck_02_covered_F_OCimport_02 {
        author = "Rabbit";
        scope = 2;
        scopeCurator = 2;
        displayName = "Covered Truck";
        side = 0;
        faction = "O_URArmy";
        crew = "O_URArmy_Rifleperson_1_01";

        class Turrets : Turrets {
            class CargoTurret_01 : CargoTurret_01 { gunnerType = ""; };
            class CargoTurret_02 : CargoTurret_02 { gunnerType = ""; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;_unit setObjectTextureGlobal [0,'\A3\soft_f_Enoch\Truck_02\Data\Truck_02_kab_EAF_co.paa'];_unit setObjectTextureGlobal [1,'\A3\soft_f_Enoch\Truck_02\Data\Truck_02_kuz_EAF_co.paa'];_unit setObjectTextureGlobal [2,'\A3\soft_f_Enoch\Truck_02\Data\Truck_02_int_EAF_co.paa'];_unit setObjectTextureGlobal [3,'\A3\soft_f_Enoch\Truck_02\Data\truck_02_chassis_EAF_CO.paa'];};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_texture = "EAF";

    };

};