#define CLASSES_MAGAZINES \
  "SWS_Magazine_60Rnd_65x39_Caseless", \
  "SWS_Magazine_60Rnd_65x39_Caseless_tracers", \
  "SWS_Magazine_60Rnd_65x39_Caseless_tracers_yellow", \
  "SWS_Magazine_60Rnd_65x39_Caseless_tracers_blue", \
  "SWS_Magazine_60Rnd_65x39_Caseless_tracers_green"

class CfgMagazines {

  //= Ammo
  class 30Rnd_65x39_caseless_msbs_mag;
  class 100Rnd_65x39_caseless_black_mag;

  #include "CfgMagazines\65x39_Caseless.inc"
};
