class CfgMagazineWells {
  class OPTRE_Magwell_MA5B {
    GVAR(Magazines)[] = {
      "OPTRE_32Rnd_762x51_Mag",
      "OPTRE_32Rnd_762x51_Mag_Tracer",
      "OPTRE_32Rnd_762x51_Mag_Tracer_Yellow"
    };
  };

  class OPTRE_Magwell_BR55 {
    GVAR(Magazines)[] = {
      // UNSC Foundries
      "36Rnd_95x40_br_55",
      "36Rnd_95x40_ap_br_55",
      "36Rnd_95x40_br_55_tracer",
      "36Rnd_95x40_ap_br_55_tracer",
      // OPTRE's tracers
      "OPTRE_36Rnd_95x40_Mag_Tracer"
    };
  };
};
