class CfgMagazineWells {
  class OPTRE_Magwell_MA5B {
    GVAR(Magazines)[] = {
      "OPTRE_32Rnd_762x51_Mag",
      "OPTRE_32Rnd_762x51_Mag_Tracer",
      "OPTRE_32Rnd_762x51_Mag_Tracer_Yellow"
    };
  };

  class OPTRE_Magwell_M45 {
    GVAR(Magazines)[] = {
      "SWS_Magazine_6Rnd_Shotgun_Incendiary",
      "SWS_Magazine_12_Rnd_Shotgun_Incendiary"
    };
  };

  class UBS_12GA {
    GVAR(Magazines)[] = {
      "SWS_Magazine_6Rnd_Shotgun_Incendiary"
    };
  };

  class OPTRE_Magwell_BR55 {
    GVAR(Magazines)[] = {
      // UNSC Foundries
      "36Rnd_95x40_br_55",
      "36Rnd_95x40_ap_br_55",
      "36Rnd_95x40_br_55_tracer",
      "36Rnd_95x40_ap_br_55_tracer",
      // OPTRE's tracers
      "OPTRE_36Rnd_95x40_Mag_Tracer"
    };
  };

  class MX_65x39_MSBS {
    GVAR(Magazines)[] = {
      "SWS_Magazine_60Rnd_65x39_Caseless_msbs",
      "SWS_Magazine_60Rnd_65x39_Caseless_msbs_Tracers",
      "SWS_Magazine_60Rnd_65x39_Caseless_msbs_Tracers_Blue",
      "SWS_Magazine_60Rnd_65x39_Caseless_msbs_Tracers_Yellow",
      "SWS_Magazine_60Rnd_65x39_Caseless_msbs_Tracers_Green"
    };
  };

  class MX_65x39 {
    GVAR(Magazines)[] = {
      "SWS_Magazine_60Rnd_65x39_Caseless",
      "SWS_Magazine_60Rnd_65x39_Caseless_Tracers",
      "SWS_Magazine_60Rnd_65x39_Caseless_Tracers_Yellow",
      "SWS_Magazine_60Rnd_65x39_Caseless_Tracers_Blue",
      "SWS_Magazine_60Rnd_65x39_Caseless_Tracers_Green"
    };
  };
};
