name = "SWS Addons"
author = "Maid"
prefix = "sws"
mainprefix = "x"

[properties]
author = "Maid"
url = "https://github.com/WitchFreya/SWSAddons"

[files]
exclude = ["*.inc"]

[hemtt.release]
archive = false
