
class CBA_Extended_EventHandlers_Base;
class EventHandlers;

#define CBA_PATCH                                                               \
    class EventHandlers : EventHandlers {                                                       \
        class CBA_Extended_EventHandlers: CBA_Extended_EventHandlers_Base {};   \
    }

class CfgVehicles {
    class AllVehicles;
    class B_APC_Wheeled_01_cannon_F;
    class B_CTRG_Soldier_AR_tna_F;
    class B_CTRG_Soldier_Exp_tna_F;
    class B_CTRG_Soldier_JTAC_tna_F;
    class B_CTRG_Soldier_LAT2_tna_F;
    class B_CTRG_Soldier_LAT_tna_F;
    class B_CTRG_Soldier_Medic_tna_F;
    class B_CTRG_Soldier_M_tna_F;
    class B_CTRG_Soldier_TL_tna_F;
    class B_CTRG_Soldier_tna_F;
    class B_diver_exp_F;
    class B_diver_F;
    class B_diver_TL_F;
    class B_engineer_F;
    class B_GEN_Commander_F;
    class B_GEN_Soldier_F;
    class B_Helipilot_F;
    class B_MBT_01_cannon_F;
    class B_medic_F;
    class B_officer_F;
    class B_Officer_Parade_F;
    class B_Plane_CAS_01_F;
    class B_RangeMaster_F;
    class B_soldier_AR_F;
    class B_soldier_exp_F;
    class B_Soldier_F;
    class B_Soldier_lite_F;
    class B_soldier_M_F;
    class B_soldier_repair_F;
    class B_Soldier_SL_F;
    class B_Soldier_Survival_F;
    class B_Soldier_TL_F;
    class B_soldier_UAV_F;
    class B_Soldier_unarmed_F;
    class B_Survivor_F;
    class B_T_diver_exp_F;
    class B_T_diver_F;
    class B_T_diver_TL_F;
    class B_T_engineer_F;
    class B_T_medic_F;
    class B_T_officer_F;
    class B_T_soldier_AR_F;
    class B_T_soldier_exp_F;
    class B_T_Soldier_F;
    class B_T_soldier_M_F;
    class B_T_soldier_repair_F;
    class B_T_soldier_SL_F;
    class B_T_soldier_TL_F;
    class B_T_soldier_UAV_F;
    class B_W_engineer_F;
    class B_W_medic_F;
    class B_W_officer_F;
    class B_W_soldier_AR_F;
    class B_W_soldier_exp_F;
    class B_W_soldier_M_F;
    class B_W_soldier_repair_F;
    class B_W_soldier_SL_F;
    class B_W_soldier_TL_F;
    class B_W_soldier_UAV_F;
    class C_IDAP_Man_AidWorker_05_F;
    class C_Journalist_01_War_F;
    class C_journalist_F;
    class C_man_1_1_F;
    class C_Man_casual_1_F;
    class C_Man_Paramedic_01_F;
    class C_man_p_fugitive_F;
    class C_Marshal_F;
    class Helicopter_Base_F;
    class Helicopter_Base_H;
    class I_diver_exp_F;
    class I_diver_F;
    class I_diver_TL_F;
    class I_E_Uniform_01_sweater_F;
    class I_G_Soldier_LAT_F;
    class I_helipilot_F;
    class I_L_Looter_Pistol_F;
    class I_L_Looter_Rifle_F;
    class I_L_Looter_SG_F;
    class I_L_Looter_SMG_F;
    class I_medic_F;
    class I_officer_F;
    class I_Officer_Parade_F;
    class I_Soldier_02_F;
    class I_Soldier_AA_F;
    class I_Soldier_A_F;
    class I_Soldier_AR_F;
    class I_Soldier_exp_F;
    class I_soldier_F;
    class I_Soldier_lite_F;
    class I_Soldier_repair_F;
    class I_Soldier_SL_F;
    class I_Soldier_unarmed_F;
    class Items_base_F;
    class I_UAV_01_F;
    class Jbad_Lamps_base_powerline;
    class Land_CampingChair_V1_F;
    class Land_Jbad_PowLines_Conc2L;
    class O_diver_exp_F;
    class O_diver_F;
    class O_diver_TL_F;
    class O_helipilot_F;
    class O_officer_F;
    class O_Officer_Parade_F;
    class OPTRE_FC_AA_Wraith;
    class OPTRE_FC_Type26B_Banshee;
    class OPTRE_FC_Type26N_Banshee;
    class OPTRE_FC_Wraith;
    class OPTRE_HEV;
    class OPTRE_M12_CIV;
    class OPTRE_M12_FAV;
    class OPTRE_M12_FAV_APC;
    class OPTRE_M494;
    class OPTRE_Pelican_armed;
    class OPTRE_Pelican_unarmed;
    class OPTRE_UNSC_falcon;
    class OPTRE_UNSC_falcon_armed;
    class OPTRE_UNSC_falcon_armed_s;
    class OPTRE_UNSC_falcon_s;
    class O_Soldier_AR_F;
    class O_Soldier_F;
    class O_Soldier_lite_F;
    class O_Soldier_SL_F;
    class O_Soldier_unarmed_F;
    class O_T_diver_exp_F;
    class O_T_diver_F;
    class O_T_diver_TL_F;
    class O_T_Officer_F;
    class O_T_Soldier_AR_F;
    class O_T_Soldier_F;
    class O_T_Soldier_SL_F;
    class O_V_Soldier_Exp_ghex_F;
    class O_V_Soldier_Exp_hex_F;
    class O_V_Soldier_ghex_F;
    class O_V_Soldier_hex_F;
    class O_V_Soldier_jtac_ghex_F;
    class O_V_Soldier_jtac_hex_F;
    class O_V_Soldier_lat_ghex_F;
    class O_V_Soldier_lat_hex_F;
    class O_V_Soldier_Medic_ghex_F;
    class O_V_Soldier_Medic_hex_F;
    class O_V_Soldier_m_ghex_F;
    class O_V_Soldier_m_hex_F;
    class O_V_Soldier_TL_ghex_F;
    class O_V_Soldier_TL_hex_F;
    class Plane_Base_F;
    class PlaneWreck;
    class PowerLines_Small_base_F;
    class StaticMGWeapon;
    class StaticMortar;
    class Tank_F;
    class TCGM_f_Apate_Flat_I_soldier;
    class TCGM_f_Apate_Flat_O_soldier;
    class TCGM_f_Apate_Flat_soldier;
    class TCGM_f_Artemis_Flat_I_soldier;
    class TCGM_f_Artemis_Flat_O_soldier;
    class TCGM_f_Artemis_Flat_soldier;
    class TCGM_f_Athena_Flat_C_soldier;
    class TCGM_f_Athena_Flat_I_soldier;
    class TCGM_f_Athena_Flat_O_soldier;
    class TCGM_f_Athena_Flat_soldier;
    class TCGM_f_Blodeuwedd_Flat_I_soldier;
    class TCGM_f_Blodeuwedd_Flat_O_soldier;
    class TCGM_f_Blodeuwedd_Flat_soldier;
    class TCGM_f_Cloaking_Flat_I_soldier;
    class TCGM_f_Cloaking_Flat_O_soldier;
    class TCGM_f_Cloaking_Flat_soldier;
    class TCGM_f_Durga_Flat_I_soldier;
    class TCGM_f_Durga_Flat_O_soldier;
    class TCGM_f_Durga_Flat_soldier;
    class TCGM_f_Gaia_Flat_I_soldier;
    class TCGM_f_Gaia_Flat_O_soldier;
    class TCGM_f_Gaia_Flat_soldier;
    class TCGM_f_Hecate_Flat_I_soldier;
    class TCGM_f_Hecate_Flat_O_soldier;
    class TCGM_f_Hecate_Flat_soldier;
    class TCGM_f_Iris_Flat_I_soldier;
    class TCGM_f_Iris_Flat_O_soldier;
    class TCGM_f_Iris_Flat_soldier;
    class TCGM_f_Kali_Flat_I_soldier;
    class TCGM_f_Kali_Flat_O_soldier;
    class TCGM_f_Kali_Flat_soldier;
    class TCGM_f_Kurukulla_Flat_I_soldier;
    class TCGM_f_Kurukulla_Flat_O_soldier;
    class TCGM_f_Kurukulla_Flat_soldier;
    class TCGM_f_Lada_Flat_I_soldier;
    class TCGM_f_Lada_Flat_O_soldier;
    class TCGM_f_Lada_Flat_soldier;
    class TCGM_f_Mania_Flat_I_soldier;
    class TCGM_f_Mania_Flat_O_soldier;
    class TCGM_f_Mania_Flat_soldier;
    class TCGM_f_Mut_Flat_I_soldier;
    class TCGM_f_Mut_Flat_O_soldier;
    class TCGM_f_Mut_Flat_soldier;
    class TCGM_f_Nyx_Flat_I_soldier;
    class TCGM_f_Nyx_Flat_O_soldier;
    class TCGM_f_Nyx_Flat_soldier;
    class TCGM_f_Ops_Flat_I_soldier;
    class TCGM_f_Ops_Flat_O_soldier;
    class TCGM_f_Ops_Flat_soldier;
    class TCGM_f_Oshun_Flat_I_soldier;
    class TCGM_f_Oshun_Flat_O_soldier;
    class TCGM_f_Oshun_Flat_soldier;
    class TCGM_f_Parvati_Flat_I_soldier;
    class TCGM_f_Parvati_Flat_O_soldier;
    class TCGM_f_Parvati_Flat_soldier;
    class TCGM_f_Radha_Flat_I_soldier;
    class TCGM_f_Radha_Flat_O_soldier;
    class TCGM_f_Radha_Flat_soldier;
    class TCGM_f_Raet_Tawy_Flat_I_soldier;
    class TCGM_f_Raet_Tawy_Flat_O_soldier;
    class TCGM_f_Raet_Tawy_Flat_soldier;
    class TCGM_f_Saraswati_Flat_I_soldier;
    class TCGM_f_Saraswati_Flat_O_soldier;
    class TCGM_f_Saraswati_Flat_soldier;
    class TCGM_f_Sekhmet_Flat_I_soldier;
    class TCGM_f_Sekhmet_Flat_O_soldier;
    class TCGM_f_Sekhmet_Flat_soldier;
    class TCGM_f_Selene_Flat_I_soldier;
    class TCGM_f_Selene_Flat_O_soldier;
    class TCGM_f_Selene_Flat_soldier;
    class TCGM_f_Sita_Flat_C_soldier;
    class TCGM_f_Sita_Flat_I_soldier;
    class TCGM_f_Sita_Flat_O_soldier;
    class TCGM_f_Sita_Flat_soldier;
    class TCGM_f_Swimsuit_Maya_civil;
    class TCGM_f_Tanit_Flat_C_soldier;
    class TCGM_f_Tanit_Flat_I_soldier;
    class TCGM_f_Tanit_Flat_O_soldier;
    class TCGM_f_Tanit_Flat_soldier;
    class TCGM_f_Tara_Flat_I_soldier;
    class TCGM_f_Tara_Flat_O_soldier;
    class TCGM_f_Tara_Flat_soldier;
    class TCGM_f_Transparent_Flat_I_soldier;
    class TCGM_f_Transparent_Flat_O_soldier;
    class TCGM_f_Transparent_Flat_soldier;
    class VTOL_Base_F;
    class B_MBT_01_cannon_F;
    class Land_Device_slingloadable_F;
    class ThingX;

    class VES_M12_APC_Base : OPTRE_M12_FAV_APC { CBA_PATCH; };
    class VES_IFV76_A : B_APC_Wheeled_01_cannon_F { CBA_PATCH; };
    class VES_M494_ORYX : OPTRE_M494 { CBA_PATCH; };
    class VES_UH144 : OPTRE_UNSC_falcon { CBA_PATCH; };
    class VES_UH144_A : OPTRE_UNSC_falcon_armed { CBA_PATCH; };
    class VES_UH144S : OPTRE_UNSC_falcon_s { CBA_PATCH; };
    class VES_UH144S_A : OPTRE_UNSC_falcon_armed_s { CBA_PATCH; };
    class VES_D77HTCI_A : OPTRE_Pelican_armed { CBA_PATCH; };
    class VES_D77HTCIS_A : VES_D77HTCI_A { CBA_PATCH; };
    class VES_D77HTCI : OPTRE_Pelican_unarmed { CBA_PATCH; };
    class VES_D77HTCIS : VES_D77HTCI { CBA_PATCH; };
    class TCGM_f_underwear_soldier : B_Survivor_F { CBA_PATCH; };
    class TCGM_f_PantiesBlack_soldier : C_Man_casual_1_F { CBA_PATCH; };
    class TCGM_RollUp_B_MTP_Soldier_AR : B_soldier_AR_F { CBA_PATCH; };
    class TCGM_RollUp_B_TNA_Soldier_AR : B_T_soldier_AR_F { CBA_PATCH; };
    class TCGM_RollUp_B_WDL_Soldier_AR : B_W_soldier_AR_F { CBA_PATCH; };
    class TCGM_RollUp_B_MTP_Medic : B_medic_F { CBA_PATCH; };
    class TCGM_RollUp_B_TNA_Medic : B_T_medic_F { CBA_PATCH; };
    class TCGM_RollUp_B_WDL_Medic : B_W_medic_F { CBA_PATCH; };
    class TCGM_RollUp_B_MTP_engineer : B_engineer_F { CBA_PATCH; };
    class TCGM_RollUp_B_TNA_engineer : B_T_engineer_F { CBA_PATCH; };
    class TCGM_RollUp_B_WDL_engineer : B_W_engineer_F { CBA_PATCH; };
    class TCGM_RollUp_B_MTP_soldier_exp : B_soldier_exp_F { CBA_PATCH; };
    class TCGM_RollUp_B_TNA_soldier_exp : B_T_soldier_exp_F { CBA_PATCH; };
    class TCGM_RollUp_B_WDL_soldier_exp : B_W_soldier_exp_F { CBA_PATCH; };
    class TCGM_RollUp_B_MTP_Soldier_M : B_soldier_M_F { CBA_PATCH; };
    class TCGM_RollUp_B_TNA_Soldier_M : B_T_soldier_M_F { CBA_PATCH; };
    class TCGM_RollUp_B_WDL_Soldier_M : B_W_soldier_M_F { CBA_PATCH; };
    class TCGM_RollUp_B_MTP_officer : B_officer_F { CBA_PATCH; };
    class TCGM_RollUp_B_TNA_officer : B_T_officer_F { CBA_PATCH; };
    class TCGM_RollUp_B_WDL_officer : B_W_officer_F { CBA_PATCH; };
    class TCGM_RollUp_B_MTP_soldier_repair : B_soldier_repair_F { CBA_PATCH; };
    class TCGM_RollUp_B_TNA_soldier_repair : B_T_soldier_repair_F { CBA_PATCH; };
    class TCGM_RollUp_B_WDL_soldier_repair : B_W_soldier_repair_F { CBA_PATCH; };
    class TCGM_RollUp_B_MTP_Soldier_LT : B_Soldier_lite_F { CBA_PATCH; };
    class TCGM_Bra_B_MTP_Soldier_SL : B_Soldier_SL_F { CBA_PATCH; };
    class TCGM_Bra_B_TNA_Soldier_SL : B_T_soldier_SL_F { CBA_PATCH; };
    class TCGM_Bra_B_WDL_Soldier_SL : B_W_soldier_SL_F { CBA_PATCH; };
    class TCGM_Bra_B_MTP_soldier_TL : B_Soldier_TL_F { CBA_PATCH; };
    class TCGM_Bra_B_TNA_soldier_TL : B_T_soldier_TL_F { CBA_PATCH; };
    class TCGM_Bra_B_WDL_soldier_TL : B_W_soldier_TL_F { CBA_PATCH; };
    class TCGM_RollUp_B_MTP_soldier_UAV : B_soldier_UAV_F { CBA_PATCH; };
    class TCGM_RollUp_B_TNA_soldier_UAV : B_T_soldier_UAV_F { CBA_PATCH; };
    class TCGM_RollUp_B_WDL_soldier_UAV : B_W_soldier_UAV_F { CBA_PATCH; };
    class TCGM_Bra_I_Sage_Looter_SMG : I_L_Looter_SMG_F { CBA_PATCH; };
    class TCGM_Bra_I_M81_Looter_Pistol : I_L_Looter_Pistol_F { CBA_PATCH; };
    class TCGM_Bra_I_M81_Looter_Rifle : I_L_Looter_Rifle_F { CBA_PATCH; };
    class TCGM_Bra_I_M81_Looter_Shotgun : I_L_Looter_SG_F { CBA_PATCH; };
    class TCGM_Stealth_B_CTRG_Soldier_TL : B_CTRG_Soldier_TL_tna_F { CBA_PATCH; };
    class TCGM_Stealth_B_CTRG_Soldier_AR : B_CTRG_Soldier_AR_tna_F { CBA_PATCH; };
    class TCGM_Stealth_B_CTRG_Soldier_SC : B_CTRG_Soldier_tna_F { CBA_PATCH; };
    class TCGM_Stealth_B_CTRG_Soldier_M : B_CTRG_Soldier_M_tna_F { CBA_PATCH; };
    class TCGM_Stealth_B_CTRG_Soldier_Exp : B_CTRG_Soldier_Exp_tna_F { CBA_PATCH; };
    class TCGM_Stealth_B_CTRG_Soldier_Medic : B_CTRG_Soldier_Medic_tna_F { CBA_PATCH; };
    class TCGM_Stealth_B_CTRG_Soldier_JTAC : B_CTRG_Soldier_JTAC_tna_F { CBA_PATCH; };
    class TCGM_Stealth_B_CTRG_Soldier_LAT2 : B_CTRG_Soldier_LAT2_tna_F { CBA_PATCH; };
    class TCGM_Stealth_B_CTRG_Soldier_LAT : B_CTRG_Soldier_LAT_tna_F { CBA_PATCH; };
    class TCGM_F_B_Mini_Range : B_RangeMaster_F { CBA_PATCH; };
    class TCGM_F_C_Mini_Journalist : C_journalist_F { CBA_PATCH; };
    class TCGM_F_C_Mini_JournalistWar : C_Journalist_01_War_F { CBA_PATCH; };
    class TCGM_F_C_Mini_Marshal : C_Marshal_F { CBA_PATCH; };
    class TCGM_F_C_Mini_IDAP : C_IDAP_Man_AidWorker_05_F { CBA_PATCH; };
    class TCGM_F_C_Mini_Navy : C_Man_casual_1_F { CBA_PATCH; };
    class TCGM_F_C_Sport_1 : C_man_1_1_F { CBA_PATCH; };
    class TCGM_Survival_Bra_B_MTP_Soldier : B_Soldier_Survival_F { CBA_PATCH; };
    class TCGM_Survival_Bra_B_TNA_Soldier : TCGM_Survival_Bra_B_MTP_Soldier { CBA_PATCH; };
    class TCGM_Viper_O_AHex_Soldier : O_V_Soldier_hex_F { CBA_PATCH; };
    class TCGM_Viper_O_GHex_Soldier : O_V_Soldier_ghex_F { CBA_PATCH; };
    class TCGM_Viper_O_UHex_Soldier : O_V_Soldier_hex_F { CBA_PATCH; };
    class TCGM_Viper_O_TL_Hex_Soldier : O_V_Soldier_TL_hex_F { CBA_PATCH; };
    class TCGM_Viper_O_TL_GHex_Soldier : O_V_Soldier_TL_ghex_F { CBA_PATCH; };
    class TCGM_Viper_O_TL_UHex_Soldier : O_V_Soldier_TL_hex_F { CBA_PATCH; };
    class TCGM_Viper_O_m_Hex_Soldier : O_V_Soldier_m_hex_F { CBA_PATCH; };
    class TCGM_Viper_O_m_GHex_Soldier : O_V_Soldier_m_ghex_F { CBA_PATCH; };
    class TCGM_Viper_O_m_UHex_Soldier : O_V_Soldier_m_hex_F { CBA_PATCH; };
    class TCGM_Viper_O_Exp_Hex_Soldier : O_V_Soldier_Exp_hex_F { CBA_PATCH; };
    class TCGM_Viper_O_Exp_GHex_Soldier : O_V_Soldier_Exp_ghex_F { CBA_PATCH; };
    class TCGM_Viper_O_Exp_UHex_Soldier : O_V_Soldier_Exp_hex_F { CBA_PATCH; };
    class TCGM_Viper_O_Medic_Hex_Soldier : O_V_Soldier_Medic_hex_F { CBA_PATCH; };
    class TCGM_Viper_O_Medic_GHex_Soldier : O_V_Soldier_Medic_ghex_F { CBA_PATCH; };
    class TCGM_Viper_O_Medic_UHex_Soldier : O_V_Soldier_Medic_hex_F { CBA_PATCH; };
    class TCGM_Viper_O_lat_Hex_Soldier : O_V_Soldier_lat_hex_F { CBA_PATCH; };
    class TCGM_Viper_O_lat_GHex_Soldier : O_V_Soldier_lat_ghex_F { CBA_PATCH; };
    class TCGM_Viper_O_lat_UHex_Soldier : O_V_Soldier_lat_hex_F { CBA_PATCH; };
    class TCGM_Viper_O_jtac_Hex_Soldier : O_V_Soldier_jtac_hex_F { CBA_PATCH; };
    class TCGM_Viper_O_jtac_GHex_Soldier : O_V_Soldier_jtac_ghex_F { CBA_PATCH; };
    class TCGM_Viper_O_jtac_UHex_Soldier : O_V_Soldier_jtac_hex_F { CBA_PATCH; };
    class TCGM_F_Diver_B : B_diver_F { CBA_PATCH; };
    class TCGM_F_Diver_B_T : B_T_diver_F { CBA_PATCH; };
    class TCGM_F_Diver_O : O_diver_F { CBA_PATCH; };
    class TCGM_F_Diver_O_T : O_T_diver_F { CBA_PATCH; };
    class TCGM_F_Diver_I : I_diver_F { CBA_PATCH; };
    class TCGM_F_Diver_B_TL : B_diver_TL_F { CBA_PATCH; };
    class TCGM_F_Diver_B_T_TL : B_T_diver_TL_F { CBA_PATCH; };
    class TCGM_F_Diver_O_TL : O_diver_TL_F { CBA_PATCH; };
    class TCGM_F_Diver_O_T_TL : O_T_diver_TL_F { CBA_PATCH; };
    class TCGM_F_Diver_I_TL : I_diver_TL_F { CBA_PATCH; };
    class TCGM_F_Diver_B_Exp : B_diver_exp_F { CBA_PATCH; };
    class TCGM_F_Diver_B_T_Exp : B_T_diver_exp_F { CBA_PATCH; };
    class TCGM_F_Diver_O_Exp : O_diver_exp_F { CBA_PATCH; };
    class TCGM_F_Diver_O_T_Exp : O_T_diver_exp_F { CBA_PATCH; };
    class TCGM_F_Diver_I_Exp : I_diver_exp_F { CBA_PATCH; };
    class TCGM_F_DiverShort_B : B_diver_F { CBA_PATCH; };
    class TCGM_F_DiverShort_B_T : B_T_diver_F { CBA_PATCH; };
    class TCGM_F_DiverShort_O : O_diver_F { CBA_PATCH; };
    class TCGM_F_DiverShort_O_T : O_T_diver_F { CBA_PATCH; };
    class TCGM_F_DiverShort_I : I_diver_F { CBA_PATCH; };
    class TCGM_F_Diver_Blu_C : TCGM_f_Swimsuit_Maya_civil { CBA_PATCH; };
    class TCGM_F_Soldier_GEN_B : B_GEN_Commander_F { CBA_PATCH; };
    class TCGM_F_Soldier1_LAT_I : I_G_Soldier_LAT_F { CBA_PATCH; };
    class TCGM_F_Soldier2_I : I_E_Uniform_01_sweater_F { CBA_PATCH; };
    class TCGM_F_Paramedic_C : C_Man_Paramedic_01_F { CBA_PATCH; };
    class TCGM_F_Soldier02_I : I_soldier_F { CBA_PATCH; };
    class TCGM_F_Soldier02_RollUp_I : I_Soldier_02_F { CBA_PATCH; };
    class TCGM_F_Soldier02_RollUp_lite_I : I_Soldier_lite_F { CBA_PATCH; };
    class TCGM_F_Soldier02_RollUp_A_I : I_Soldier_A_F { CBA_PATCH; };
    class TCGM_F_Soldier02_RollUp_AR_I : I_Soldier_AR_F { CBA_PATCH; };
    class TCGM_F_Soldier02_RollUp_SL_I : I_Soldier_SL_F { CBA_PATCH; };
    class TCGM_F_Soldier02_RollUp_AA_I : I_Soldier_AA_F { CBA_PATCH; };
    class TCGM_F_Soldier02_RollUp_medic_I : I_medic_F { CBA_PATCH; };
    class TCGM_F_Soldier02_RollUp_repair_I : I_Soldier_repair_F { CBA_PATCH; };
    class TCGM_F_Soldier02_RollUp_exp_I : I_Soldier_exp_F { CBA_PATCH; };

    class DMNS_Shortsword_01_wreck_F : PlaneWreck { CBA_PATCH; };
    class Land_OPTRE_barrel_hydrogen : Items_base_F { CBA_PATCH; };
    class Land_OPTRE_fusion_coil : Items_base_F { CBA_PATCH; };
    class OPTRE_M12_CIV : OPTRE_M12_FAV { CBA_PATCH; };
    class OPTRE_HEV : StaticMGWeapon { CBA_PATCH; };
    class OPTRE_Pelican_F : Helicopter_Base_H { CBA_PATCH; };
    class OPTRE_Objects_Wreck_Pelican : PlaneWreck { CBA_PATCH; };
    class OPTRE_EscapePod_Base : Plane_Base_F { CBA_PATCH; };
    class OPTRE_RCHog : OPTRE_M12_CIV { CBA_PATCH; };
    class OPTRE_Sabre_Wreck_F : PlaneWreck { CBA_PATCH; };
    class unscdrone_wreck_F : PlaneWreck { CBA_PATCH; };
    class OPTRE_Objects_Wreck_Falcon : PlaneWreck { CBA_PATCH; };
    class DMNS_SOEIV : StaticMGWeapon { CBA_PATCH; };
    class OPTRE_FC_Type26B_Banshee : B_Plane_CAS_01_F { CBA_PATCH; };
    class OPTRE_FC_Type26N_Banshee : OPTRE_FC_Type26B_Banshee { CBA_PATCH; };
    class OPTRE_FC_Type27_Banshee : OPTRE_FC_Type26N_Banshee { CBA_PATCH; };
    class OPTRE_FC_Wraith : B_MBT_01_cannon_F { CBA_PATCH; };
    class OPTRE_FC_AA_Wraith : OPTRE_FC_Wraith { CBA_PATCH; };
    class OPTRE_FC_AA_Wraith_NOFLAK : OPTRE_FC_AA_Wraith { CBA_PATCH; };
    class OPTRE_FC_AA_Wraith_Needle : OPTRE_FC_Wraith { CBA_PATCH; };
    class OPTRE_FC_Wraith_Tank : OPTRE_FC_Wraith { CBA_PATCH; };
    class OPTRE_FC_Spectre_AI_Base : B_MBT_01_cannon_F { CBA_PATCH; };
    class OPTRE_FC_Spirit_F : Helicopter_Base_F { CBA_PATCH; };
    class 11_Mortar_base : StaticMortar { CBA_PATCH; };
    class WB_Officer_Parade_F : B_Officer_Parade_F { CBA_PATCH; };
    class WO_Officer_Parade_F : O_Officer_Parade_F { CBA_PATCH; };
    class WI_Officer_Parade_F : I_Officer_Parade_F { CBA_PATCH; };
    class WO_helipilot_F : O_helipilot_F { CBA_PATCH; };
    class WI_helipilot_F : I_helipilot_F { CBA_PATCH; };
    class WB_Helipilot_F : B_Helipilot_F { CBA_PATCH; };
    class WO_diver_F : O_diver_F { CBA_PATCH; };
    class WO_T_Soldier_SL_F : O_T_Soldier_SL_F { CBA_PATCH; };
    class WO_T_Soldier_AR_F : O_T_Soldier_AR_F { CBA_PATCH; };
    class WO_T_Soldier_F : O_T_Soldier_F { CBA_PATCH; };
    class WO_Soldier_lite_F : O_Soldier_lite_F { CBA_PATCH; };
    class WO_Soldier_SL_F : O_Soldier_SL_F { CBA_PATCH; };
    class WO_Soldier_AR_F : O_Soldier_AR_F { CBA_PATCH; };
    class WO_Soldier_F : O_Soldier_F { CBA_PATCH; };
    class WO_T_Officer_F : O_T_Officer_F { CBA_PATCH; };
    class WO_officer_F : O_officer_F { CBA_PATCH; };
    class WI_officer_F : I_officer_F { CBA_PATCH; };
    class WI_soldier_F : I_soldier_F { CBA_PATCH; };
    class WI_Soldier_AR_F : I_Soldier_AR_F { CBA_PATCH; };
    class WB_officer_F : B_officer_F { CBA_PATCH; };
    class WB_T_officer_F : B_T_Officer_F { CBA_PATCH; };
    class WB_T_Soldier_F : B_T_Soldier_F { CBA_PATCH; };
    class WB_Soldier_F : B_Soldier_F { CBA_PATCH; };
    class WB_soldier_AR_F : B_soldier_AR_F { CBA_PATCH; };
    class WB_T_Soldier_AR_F : B_T_Soldier_AR_F { CBA_PATCH; };
    class WB_diver_F : B_diver_F { CBA_PATCH; };
    class WB_diver2_F : B_diver_F { CBA_PATCH; };
    class WB_GEN_Soldier_F : B_GEN_Soldier_F { CBA_PATCH; };
    class WB_GEN_Commander_F : B_GEN_Commander_F { CBA_PATCH; };
    class max_female_b : C_man_p_fugitive_F { CBA_PATCH; };
    class B_CBRN_Unarmed : B_Soldier_unarmed_F { CBA_PATCH; };
    class O_CBRN_Unarmed : O_Soldier_unarmed_F { CBA_PATCH; };
    class I_CBRN_Unarmed : I_Soldier_unarmed_F { CBA_PATCH; };
    class TCGM_f_Oshun_Flat_soldier : B_Soldier_F { CBA_PATCH; };
    class TCGM_m_Midas_Flat_soldier : TCGM_f_Oshun_Flat_soldier { CBA_PATCH; };
    class TCGM_m_Argiron_Flat_soldier : TCGM_f_Selene_Flat_soldier { CBA_PATCH; };
    class TCGM_m_Hephaestus_Flat_soldier : TCGM_f_Gaia_Flat_soldier { CBA_PATCH; };
    class TCGM_m_Dactyls_Flat_soldier : TCGM_f_Lada_Flat_soldier { CBA_PATCH; };
    class TCGM_m_Melqart_Flat_soldier : TCGM_f_Tanit_Flat_soldier { CBA_PATCH; };
    class TCGM_m_Rama_Flat_soldier : TCGM_f_Kali_Flat_soldier { CBA_PATCH; };
    class TCGM_m_Mars_Flat_soldier : TCGM_f_Kurukulla_Flat_soldier { CBA_PATCH; };
    class TCGM_m_Parameshvara_Flat_soldier : TCGM_f_Saraswati_Flat_soldier { CBA_PATCH; };
    class TCGM_m_Indra_Flat_soldier : TCGM_f_Radha_Flat_soldier { CBA_PATCH; };
    class TCGM_m_Amun_Flat_soldier : TCGM_f_Mut_Flat_soldier { CBA_PATCH; };
    class TCGM_m_Vishnu_Flat_soldier : TCGM_f_Sita_Flat_soldier { CBA_PATCH; };
    class TCGM_m_Saturn_Flat_soldier : TCGM_f_Ops_Flat_soldier { CBA_PATCH; };
    class TCGM_m_Hanuman_Flat_soldier : TCGM_f_Durga_Flat_soldier { CBA_PATCH; };
    class TCGM_m_Proteus_Flat_soldier : TCGM_f_Apate_Flat_soldier { CBA_PATCH; };
    class TCGM_m_Min_Flat_soldier : TCGM_f_Hecate_Flat_soldier { CBA_PATCH; };
    class TCGM_m_Vulcan_Flat_soldier : TCGM_f_Sekhmet_Flat_soldier { CBA_PATCH; };
    class TCGM_m_Osiris_Flat_soldier : TCGM_f_Artemis_Flat_soldier { CBA_PATCH; };
    class TCGM_m_Inti_Flat_soldier : TCGM_f_Raet_Tawy_Flat_soldier { CBA_PATCH; };
    class TCGM_m_Apollo_Flat_soldier : TCGM_f_Athena_Flat_soldier { CBA_PATCH; };
    class TCGM_m_Shiva_Flat_soldier : TCGM_f_Tara_Flat_soldier { CBA_PATCH; };
    class TCGM_m_Janus_Flat_soldier : TCGM_f_Parvati_Flat_soldier { CBA_PATCH; };
    class TCGM_m_Rakshasa_Flat_soldier : TCGM_f_Blodeuwedd_Flat_soldier { CBA_PATCH; };
    class TCGM_m_Erebus_Flat_soldier : TCGM_f_Nyx_Flat_soldier { CBA_PATCH; };
    class TCGM_m_Hermes_Flat_soldier : TCGM_f_Iris_Flat_soldier { CBA_PATCH; };
    class TCGM_m_Dionysus_Flat_soldier : TCGM_f_Mania_Flat_soldier { CBA_PATCH; };
    class TCGM_m_Transparent_Flat_soldier : TCGM_f_Transparent_Flat_soldier { CBA_PATCH; };
    class TCGM_m_Cloaking_Flat_soldier : TCGM_f_Cloaking_Flat_soldier { CBA_PATCH; };
    class TCGM_m_Midas_Flat_O_soldier : TCGM_f_Oshun_Flat_O_soldier { CBA_PATCH; };
    class TCGM_m_Argiron_Flat_O_soldier : TCGM_f_Selene_Flat_O_soldier { CBA_PATCH; };
    class TCGM_m_Hephaestus_Flat_O_soldier : TCGM_f_Gaia_Flat_O_soldier { CBA_PATCH; };
    class TCGM_m_Dactyls_Flat_O_soldier : TCGM_f_Lada_Flat_O_soldier { CBA_PATCH; };
    class TCGM_m_Melqart_Flat_O_soldier : TCGM_f_Tanit_Flat_O_soldier { CBA_PATCH; };
    class TCGM_m_Rama_Flat_O_soldier : TCGM_f_Kali_Flat_O_soldier { CBA_PATCH; };
    class TCGM_m_Mars_Flat_O_soldier : TCGM_f_Kurukulla_Flat_O_soldier { CBA_PATCH; };
    class TCGM_m_Parameshvara_Flat_O_soldier : TCGM_f_Saraswati_Flat_O_soldier { CBA_PATCH; };
    class TCGM_m_Indra_Flat_O_soldier : TCGM_f_Radha_Flat_O_soldier { CBA_PATCH; };
    class TCGM_m_Amun_Flat_O_soldier : TCGM_f_Mut_Flat_O_soldier { CBA_PATCH; };
    class TCGM_m_Vishnu_Flat_O_soldier : TCGM_f_Sita_Flat_O_soldier { CBA_PATCH; };
    class TCGM_m_Saturn_Flat_O_soldier : TCGM_f_Ops_Flat_O_soldier { CBA_PATCH; };
    class TCGM_m_Hanuman_Flat_O_soldier : TCGM_f_Durga_Flat_O_soldier { CBA_PATCH; };
    class TCGM_m_Proteus_Flat_O_soldier : TCGM_f_Apate_Flat_O_soldier { CBA_PATCH; };
    class TCGM_m_Min_Flat_O_soldier : TCGM_f_Hecate_Flat_O_soldier { CBA_PATCH; };
    class TCGM_m_Vulcan_Flat_O_soldier : TCGM_f_Sekhmet_Flat_O_soldier { CBA_PATCH; };
    class TCGM_m_Osiris_Flat_O_soldier : TCGM_f_Artemis_Flat_O_soldier { CBA_PATCH; };
    class TCGM_m_Inti_Flat_O_soldier : TCGM_f_Raet_Tawy_Flat_O_soldier { CBA_PATCH; };
    class TCGM_m_Apollo_Flat_O_soldier : TCGM_f_Athena_Flat_O_soldier { CBA_PATCH; };
    class TCGM_m_Shiva_Flat_O_soldier : TCGM_f_Tara_Flat_O_soldier { CBA_PATCH; };
    class TCGM_m_Janus_Flat_O_soldier : TCGM_f_Parvati_Flat_O_soldier { CBA_PATCH; };
    class TCGM_m_Rakshasa_Flat_O_soldier : TCGM_f_Blodeuwedd_Flat_O_soldier { CBA_PATCH; };
    class TCGM_m_Dionysus_Flat_O_soldier : TCGM_f_Mania_Flat_O_soldier { CBA_PATCH; };
    class TCGM_m_Erebus_Flat_O_soldier : TCGM_f_Nyx_Flat_O_soldier { CBA_PATCH; };
    class TCGM_m_Transparent_Flat_O_soldier : TCGM_f_Transparent_Flat_O_soldier { CBA_PATCH; };
    class TCGM_m_Cloaking_Flat_O_soldier : TCGM_f_Cloaking_Flat_O_soldier { CBA_PATCH; };
    class TCGM_m_Hermes_Flat_O_soldier : TCGM_f_Iris_Flat_O_soldier { CBA_PATCH; };
    class TCGM_m_Midas_Flat_I_soldier : TCGM_f_Oshun_Flat_I_soldier { CBA_PATCH; };
    class TCGM_m_Argiron_Flat_I_soldier : TCGM_f_Selene_Flat_I_soldier { CBA_PATCH; };
    class TCGM_m_Hephaestus_Flat_I_soldier : TCGM_f_Gaia_Flat_I_soldier { CBA_PATCH; };
    class TCGM_m_Dactyls_Flat_I_soldier : TCGM_f_Lada_Flat_I_soldier { CBA_PATCH; };
    class TCGM_m_Melqart_Flat_I_soldier : TCGM_f_Tanit_Flat_I_soldier { CBA_PATCH; };
    class TCGM_m_Rama_Flat_I_soldier : TCGM_f_Kali_Flat_I_soldier { CBA_PATCH; };
    class TCGM_m_Mars_Flat_I_soldier : TCGM_f_Kurukulla_Flat_I_soldier { CBA_PATCH; };
    class TCGM_m_Parameshvara_Flat_I_soldier : TCGM_f_Saraswati_Flat_I_soldier { CBA_PATCH; };
    class TCGM_m_Indra_Flat_I_soldier : TCGM_f_Radha_Flat_I_soldier { CBA_PATCH; };
    class TCGM_m_Amun_Flat_I_soldier : TCGM_f_Mut_Flat_I_soldier { CBA_PATCH; };
    class TCGM_m_Vishnu_Flat_I_soldier : TCGM_f_Sita_Flat_I_soldier { CBA_PATCH; };
    class TCGM_m_Saturn_Flat_I_soldier : TCGM_f_Ops_Flat_I_soldier { CBA_PATCH; };
    class TCGM_m_Hanuman_Flat_I_soldier : TCGM_f_Durga_Flat_I_soldier { CBA_PATCH; };
    class TCGM_m_Proteus_Flat_I_soldier : TCGM_f_Apate_Flat_I_soldier { CBA_PATCH; };
    class TCGM_m_Min_Flat_I_soldier : TCGM_f_Hecate_Flat_I_soldier { CBA_PATCH; };
    class TCGM_m_Vulcan_Flat_I_soldier : TCGM_f_Sekhmet_Flat_I_soldier { CBA_PATCH; };
    class TCGM_m_Osiris_Flat_I_soldier : TCGM_f_Artemis_Flat_I_soldier { CBA_PATCH; };
    class TCGM_m_Inti_Flat_I_soldier : TCGM_f_Raet_Tawy_Flat_I_soldier { CBA_PATCH; };
    class TCGM_m_Apollo_Flat_I_soldier : TCGM_f_Athena_Flat_I_soldier { CBA_PATCH; };
    class TCGM_m_Shiva_Flat_I_soldier : TCGM_f_Tara_Flat_I_soldier { CBA_PATCH; };
    class TCGM_m_Janus_Flat_I_soldier : TCGM_f_Parvati_Flat_I_soldier { CBA_PATCH; };
    class TCGM_m_Rakshasa_Flat_I_soldier : TCGM_f_Blodeuwedd_Flat_I_soldier { CBA_PATCH; };
    class TCGM_m_Dionysus_Flat_I_soldier : TCGM_f_Mania_Flat_I_soldier { CBA_PATCH; };
    class TCGM_m_Erebus_Flat_I_soldier : TCGM_f_Nyx_Flat_I_soldier { CBA_PATCH; };
    class TCGM_m_Transparent_Flat_I_soldier : TCGM_f_Transparent_Flat_I_soldier { CBA_PATCH; };
    class TCGM_m_Cloaking_Flat_I_soldier : TCGM_f_Cloaking_Flat_I_soldier { CBA_PATCH; };
    class TCGM_m_Hermes_Flat_I_soldier : TCGM_f_Iris_Flat_I_soldier { CBA_PATCH; };
    class TCGM_m_Melqart_Flat_C_soldier : TCGM_f_Tanit_Flat_C_soldier { CBA_PATCH; };
    class TCGM_m_Vishnu_Flat_C_soldier : TCGM_f_Sita_Flat_C_soldier { CBA_PATCH; };
    class TCGM_m_Apollo_Flat_C_soldier : TCGM_f_Athena_Flat_C_soldier { CBA_PATCH; };
    class Jbad_CraneCon : Tank_F { CBA_PATCH; };
    class bench_1 : Land_CampingChair_V1_F { CBA_PATCH; };
    class bench_2 : Land_CampingChair_V1_F { CBA_PATCH; };
    class bench_2B : Land_CampingChair_V1_F { CBA_PATCH; };
    class Jbad_Lamps_base_powerline : PowerLines_Small_base_F { CBA_PATCH; };
    class Land_Jbad_PowLineB : Jbad_Lamps_base_powerline { CBA_PATCH; };
    class Land_Jbad_Pole_withlight : Land_Jbad_PowLines_Conc2L { CBA_PATCH; };
    class Land_Jbad_Pole_Speaker : Land_Jbad_PowLines_Conc2L { CBA_PATCH; };
    class Land_Jbad_Pole_1 : Jbad_Lamps_base_powerline { CBA_PATCH; };
    class SZ_Sofa : Land_CampingChair_V1_F { CBA_PATCH; };
    class SZ_stool : Land_CampingChair_V1_F { CBA_PATCH; };
    class SZ_Chair : Land_CampingChair_V1_F { CBA_PATCH; };
    class Hogosha_D77HTCI_A : OPTRE_Pelican_armed { CBA_PATCH; };
    class OPTRE_FC_Locust : B_MBT_01_cannon_F { CBA_PATCH; };
    class Crows_Emp_Device : Land_Device_slingloadable_F { CBA_PATCH; };
    class Lantern_01_base_F : ThingX { CBA_PATCH; };
    class SpaceshipCapsule_01_F : ThingX { CBA_PATCH; };
    class OPTRE_FC_Spectre_Base : B_MBT_01_cannon_F { CBA_PATCH; };
    class OPTRE_FC_SAM_Wraith_Needle : OPTRE_FC_Wraith { CBA_PATCH; };
};
