class XtdGearInfos {
    class CfgWeapons {
        class OPTRE_M45 {
            model = "OPTRE_Shotgun";
            version = "M45";
            variant = "Standard";
        };
        class OPTRE_M45Tac {
            model = "OPTRE_Shotgun";
            version = "M45";
            variant = "Tactical";
        };
        class OPTRE_M45A {
            model = "OPTRE_Shotgun";
            version = "M45A";
            variant = "Standard";
        };
        class OPTRE_M45ATac {
            model = "OPTRE_Shotgun";
            version = "M45A";
            variant = "Tactical";
        };
        class OPTRE_M45E {
            model = "OPTRE_Shotgun";
            version = "M45E";
            variant = "Standard";
        };
        class OPTRE_M90A {
            model = "OPTRE_Shotgun";
            version = "M90A";
            variant = "Standard";
        };
    };
};
