
class CfgVehicles {
    class AllVehicles;
    class VTOL_Base_F;

    //== Correct class pollution that shouldn't exist at base level
    class UniformItem: AllVehicles {};
    class Turrets: AllVehicles {};
    class B_T_LSV_02_unarmed_olive_F: AllVehicles {};
    class pilotCamera : AllVehicles {};
    class N19_D77HTCIS_A : AllVehicles {};
    class N19_D77HTCIS_A_OCimport_01 : AllVehicles {};
    class N19_D77HTCIS_A_OCimport_02 : AllVehicles {};
    class 19_M12_APC_WHQ : AllVehicles {};
    class 19_M12_APC_WHQ_OCimport_01 : AllVehicles {};
    class 19_M12_APC_WHQ_OCimport_02 : AllVehicles {};
    class 19_M813_TT_WHQ : AllVehicles {};
    class 19_M813_TT_WHQ_OCimport_01 : AllVehicles {};
    class 19_M813_TT_WHQ_OCimport_02 : AllVehicles {};
    class 19_M12A1_LRV_WHQ : AllVehicles {};
    class 19_M12A1_LRV_WHQ_OCimport_01 : AllVehicles {};
    class 19_M12A1_LRV_WHQ_OCimport_02 : AllVehicles {};
    class 19_M12G1_LRV_WHQ : AllVehicles {};
    class 19_M12G1_LRV_WHQ_OCimport_01 : AllVehicles {};
    class 19_M12G1_LRV_WHQ_OCimport_02 : AllVehicles {};
    class 19_M12_LRV_WHQ : AllVehicles {};
    class 19_M12_LRV_WHQ_OCimport_01 : AllVehicles {};
    class 19_M12_LRV_WHQ_OCimport_02 : AllVehicles {};
    class O_soldier_Melee : AllVehicles {};
    class O_soldier_Melee_RUSH : AllVehicles {};
    class 41st_Assassin_Melee : AllVehicles {};
    class MainTurret : AllVehicles {};
    class ViewGunner : AllVehicles {};
    class ViewCargo : AllVehicles {};
    class ViewPilot : AllVehicles {};
    class Narrow : AllVehicles {};
    class Medium : AllVehicles {};
    class Wide : AllVehicles {};
    class textureSources : AllVehicles {};
    class CopilotTurret : AllVehicles {};
    class GunnerTurret : AllVehicles {};
    class CargoTurret : AllVehicles {};
    class ViewOptics : AllVehicles {};
    class Components : AllVehicles {};
    class CargoTurret_01 : AllVehicles {};
    class CargoTurret_02 : AllVehicles {};
    class AssembleInfo : AllVehicles {};
    class ACE_SelfActions : AllVehicles {};
    class VehicleSystemsTemplateLeftCommander : AllVehicles {};
    class VehicleSystemsTemplateRightCommander : AllVehicles {};
    class CommanderOptics : AllVehicles {};
    class DefaultVehicleSystemsDisplayManagerLeft : AllVehicles {};
    class DefaultVehicleSystemsDisplayManagerRight : AllVehicles {};

    delete UniformItem;
    delete Turrets;
    delete B_T_LSV_02_unarmed_olive_F;
    delete pilotCamera;
    delete N19_D77HTCIS_A;
    delete N19_D77HTCIS_A_OCimport_01;
    delete N19_D77HTCIS_A_OCimport_02;
    delete 19_M12_APC_WHQ;
    delete 19_M12_APC_WHQ_OCimport_01;
    delete 19_M12_APC_WHQ_OCimport_02;
    delete 19_M813_TT_WHQ;
    delete 19_M813_TT_WHQ_OCimport_01;
    delete 19_M813_TT_WHQ_OCimport_02;
    delete 19_M12A1_LRV_WHQ;
    delete 19_M12A1_LRV_WHQ_OCimport_01;
    delete 19_M12A1_LRV_WHQ_OCimport_02;
    delete 19_M12G1_LRV_WHQ;
    delete 19_M12G1_LRV_WHQ_OCimport_01;
    delete 19_M12G1_LRV_WHQ_OCimport_02;
    delete 19_M12_LRV_WHQ;
    delete 19_M12_LRV_WHQ_OCimport_01;
    delete 19_M12_LRV_WHQ_OCimport_02;
    delete O_soldier_Melee;
    delete O_soldier_Melee_RUSH;
    delete 41st_Assassin_Melee;
    delete MainTurret;
    delete ViewGunner;
    delete ViewCargo;
    delete ViewPilot;
    delete Narrow;
    delete Medium;
    delete Wide;
    delete textureSources;
    delete CopilotTurret;
    delete GunnerTurret;
    delete CargoTurret;
    delete ViewOptics;
    delete Components;
    delete CargoTurret_01;
    delete CargoTurret_02;
    delete AssembleInfo;
    delete ACE_SelfActions;
    delete VehicleSystemsTemplateLeftCommander;
    delete VehicleSystemsTemplateRightCommander;
    delete CommanderOptics;
    delete DefaultVehicleSystemsDisplayManagerLeft;
    delete DefaultVehicleSystemsDisplayManagerRight;
};
