class SWS_Weapon_AR0M37 : LM_OPCAN_AR0M37
{
  class XtdGearInfo
  {
    model = "SWS_Weapon_Autorifles";
    underbarrel = "None";
    body = "0M37S";
    variant = "Standard";
  };
};

class SWS_Weapon_AR0M37_GL : LM_OPCAN_AR0M37_GL
{
  class XtdGearInfo
  {
    model = "SWS_Weapon_Autorifles";
    underbarrel = "GL";
    body = "0M37S";
    variant = "Standard";
  };
};

class SWS_Weapon_AR0M37_SHT : LM_OPCAN_AR0M37_SHT
{
  class XtdGearInfo
  {
    model = "SWS_Weapon_Autorifles";
    underbarrel = "SHT";
    body = "0M37S";
    variant = "Standard";
  };
};
class SWS_Weapon_AR0M37S_Hound : SWS_Weapon_AR0M37
{
  class XtdGearInfo : XtdGearInfo
  {
    variant = "Hound";
  };
};
class SWS_Weapon_AR0M37S_Hound_GL : SWS_Weapon_AR0M37_GL
{
  class XtdGearInfo : XtdGearInfo
  {
    variant = "Hound";
  };
};
class SWS_Weapon_AR0M37S_Hound_SHT : SWS_Weapon_AR0M37_SHT
{
  class XtdGearInfo : XtdGearInfo
  {
    variant = "Hound";
  };
};
