class CfgVehicles {
  class OPTRE_Wombat_B;
  class OPTRE_Wombat_S;
  class OPTRE_Wombat;

  class VES_F99 : OPTRE_Wombat_S {
    displayName = "F-99 Wombat";
    crew = "B_UAV_AI";
  };
  class VES_F99_Gunpod : OPTRE_Wombat {
    displayName = "F-99 Wombat (Gunpod)";
    crew = "B_UAV_AI";
  };
  class VES_F99_Missile : OPTRE_Wombat_B {
    displayName = "F-99 Wombat (Missile)";
    crew = "B_UAV_AI";
  };
};
