class XtdGearInfos {
  class CfgWeapons {
    class 41st_Away_Vest_5 {
      model = "41st_Away_Vest";
      role = "Heavy";
    };
    class 41st_Away_Vest_3 {
      model = "41st_Away_Vest";
      role = "Light";
    };
    class 41st_Away_Vest_4 {
      model = "41st_Away_Vest";
      role = "Marksman";
    };
    class 41st_Away_Vest_6 {
      model = "41st_Away_Vest";
      role = "Medic";
    };
    class 41st_Away_Vest_1 {
      model = "41st_Away_Vest";
      role = "Rifleman";
    };
    class 41st_Away_Vest_2 {
      model = "41st_Away_Vest";
      role = "Team_Lead";
    };
  };
};
