
class CfgMagazines {
	class 150Rnd_762x51_Box;

  // m33t LMG
	class DMNS_100Rnd_762x51_Mag: 150Rnd_762x51_Box {
    mass = 30;
  };
	class DMNS_200Rnd_762x51_Mag: DMNS_100Rnd_762x51_Mag {
    mass = 60;
  };
	class DMNS_400Rnd_762x51_Mag: DMNS_200Rnd_762x51_Mag {
    mass = 120;
  };
};
class CfgMagazines {
	class 36Rnd_95x40_br_55;
	class 36Rnd_95x40_ap_br_55: 36Rnd_95x40_br_55 {
    mass = 20;
  };
};
