class CfgAmmo {
  class ACE_338_Ball_API526;
  class SWS_338_Abyssal : ACE_338_Ball_API526 {
    ace_vehicle_damage_incendiary = 0;
    ace_muzzleVelocities[] = {1067};
    ace_muzzleVelocityVariationSD = 0.1;
    ace_bulletLength = 41.4528;
    ace_bulletMass = 19.7637;
    ace_caliber = 8.585;

    airFriction = -0.00065414;
    caliber = 3.8;
    hit = 18;
    typicalSpeed = 1067;
    tracerScale = 1.3;
  };
};
