name: Build

on:
  push:
    branches: [main]
    tags:
      - v*
  pull_request:
    branches: [main]

jobs:
  build:
    name: Build
    runs-on: windows-latest
    steps:
      # A3 tools necessary for HEMTT binarization
      - name: Install Arma 3 Tools
        uses: arma-actions/arma3-tools@master
        with:
          toolsUrl: ${{ secrets.A3_TOOLS_URL }}
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup HEMTT
        uses: arma-actions/hemtt@v1
      - name: Run HEMTT build
        run: hemtt release
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: sws-${{ github.sha }}
          path: releases/sws-latest.zip
          if-no-files-found: error
          compression-level: 0 # Big files aren't compressed easily

  release:
    name: Release
    if: startsWith(github.ref, 'refs/tags/') && ! contains(github.event.head_commit.message, '[ci skip]')
    runs-on: ubuntu-latest
    needs:
      - build
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Download Release
        uses: actions/download-artifact@v3
        with:
          name: sws-${{ github.sha }}
      - name: Rename Release
        run: mv sws-latest.zip sws-${{ github.ref_name }}.zip
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: sws-${{ github.ref_name }}.zip
          draft: true

