name: HEMTT

on: [push]

jobs:
  hemtt:
    name: HEMTT
    runs-on: windows-latest
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    steps:
      - name: Install Arma 3 Tools
        uses: arma-actions/arma3-tools@master
        with:
          toolsUrl: ${{ secrets.A3_TOOLS_URL }}
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup HEMTT
        uses: arma-actions/hemtt@v1
      - name: Run HEMTT check
        run: hemtt check

