class ACEX_Fortify_Presets {
	class SWS_Fortify_Preset {
		displayName = "SWS Preset";
		objects[] = {
			{"Land_BagFence_Short_F", 5},
			{"Land_BagFence_Round_F", 5},
			{"Land_BagFence_Long_F", 10},
			{"Land_Cargo_Patrol_V3_F", 30},
			{"Land_BagBunker_Small_F", 15},
			{"Land_BagBunker_Large_F", 30},
			{"Land_BagBunker_Tower_F", 25},
			{"Land_OPTRE_watchtower_woodland", 30},
			{"Land_OPTRE_barrel_hydrogen", 10},
			{"DMNS_UNSC_Barricade_01", 15},
			{"jbad_steps", 15},
			{"jbad_Wall_IndCnc_4", 20},
			{"ACE_ConcertinaWireCoil", 15}
		};
	};
};
