class ACEX_Fortify_Presets {
	class SWS_Fortify_Preset {
		displayName = "SWS Preset";
		objects[] = {
			{"Land_BagFence_Short_F", 2},
			{"Land_BagFence_Round_F", 4},
			{"Land_BagFence_Long_F", 4},
			{"Land_Cargo_Patrol_V3_F", 32},
			{"Land_BagBunker_Small_F", 12},
			{"Land_BagBunker_Large_F", 30},
			{"Land_BagBunker_Tower_F", 26},
			{"Land_OPTRE_watchtower_woodland", 34},
			{"Land_OPTRE_barrel_hydrogen", 10},
			{"DMNS_UNSC_Barricade_01", 14},
			{"jbad_steps", 12},
			{"jbad_Wall_IndCnc_4", 20},
			{"ACE_ConcertinaWireCoil", 4}
		};
	};

    class SWS_Fortify_Preset_Minimal {
		displayName = "SWS Preset (Light)";
		objects[] = {
			{"Land_BagFence_Short_F", 2},
			{"Land_BagFence_Round_F", 4},
			{"Land_BagFence_Long_F", 4},
			{"Land_BagBunker_Small_F", 12},
			{"Land_BagBunker_Large_F", 30},
			{"Land_BagBunker_Tower_F", 26},
			{"jbad_steps", 12},
			{"ACE_ConcertinaWireCoil", 4}
		};
	};
};
